### ISSUE TITLE
Endpoint not logging location

### ISSUE THREAD

**Issue by alex-phillips** [Freika/dawarich#10]
When I attempt to hit the endpoint with my location, the following error gets logged in the docker container. Not sure if this is a database permissions issue? I'm using a DB instance that existed prior to this application, so the user creation was done externally, but the user owns the database created.

```
dawarich-app      | 14:23:00 web.1  | Started POST "/api/v1/points?api_key=[FILTERED]" for 172.18.1.1 at 2024-04-07 14:23:00 +0000
dawarich-app      | 14:23:00 web.1  |   ActiveRecord::SchemaMigration Load (5.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich-app      | 14:23:00 web.1  | Processing by Api::V1::PointsController#create as HTML
dawarich-app      | 14:23:00 web.1  |   Parameters: {"_type"=>"location", "BSSID"=>"REMOVED", "SSID"=>"REMOVED", "acc"=>47, "alt"=>98, "batt"=>83, "bs"=>1, "conn"=>"w", "created_at"=>1712499781, "lat"=>REMOVED, "lon"=>REMOVED, "m"=>1, "t"=>"p", "tid"=>"ap", "topic"=>"owntracks/my_name/phone", "tst"=>1712497765, "vac"=>6, "vel"=>0, "api_key"=>"[FILTERED]", "point"=>{"topic"=>"owntracks/my_name/phone", "created_at"=>1712499781}}
dawarich-app      | 14:23:00 web.1  | Unpermitted parameters: :created_at, :api_key. Context: { controller: Api::V1::PointsController, action: create, request: #<ActionDispatch::Request:0x00007f123d185500>, params: {"_type"=>"location", "BSSID"=>"REMOVED", "SSID"=>"REMOVED", "acc"=>47, "alt"=>98, "batt"=>83, "bs"=>1, "conn"=>"w", "created_at"=>1712499781, "lat"=>REMOVED, "lon"=>REMOVED, "m"=>1, "t"=>"p", "tid"=>"ap", "topic"=>"owntracks/my_name/phone", "tst"=>1712497765, "vac"=>6, "vel"=>0, "api_key"=>"[FILTERED]", "controller"=>"api/v1/points", "action"=>"create", "point"=>{"topic"=>"owntracks/my_name/phone", "created_at"=>1712499781}} }
dawarich-app      | 14:23:00 web.1  | 2024-04-07T14:23:00.860Z pid=44 tid=ei8 INFO: Sidekiq 7.2.2 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://redis:6379/7"}
dawarich-app      | 14:23:00 web.1  | [ActiveJob] Enqueued PointCreatingJob (Job ID: ddb764bb-4842-4806-85a8-910ff285fcbd) to Sidekiq(default) with arguments: #<ActionController::Parameters {"lat"=>REMOVED, "lon"=>REMOVED, "bs"=>1, "batt"=>83, "alt"=>98, "acc"=>47, "vac"=>6, "vel"=>0, "conn"=>"w", "SSID"=>"REMOVED", "BSSID"=>"REMOVED", "m"=>1, "tid"=>"ap", "tst"=>1712497765, "topic"=>"owntracks/my_name/phone", "_type"=>"location", "t"=>"p", "point"=>#<ActionController::Parameters {"topic"=>"owntracks/my_name/phone", "created_at"=>1712499781} permitted: true>} permitted: true>
dawarich-app      | 14:23:00 web.1  | [ActiveJob] ↳ app/controllers/api/v1/points_controller.rb:5:in `create'
dawarich-app      | 14:23:00 web.1  | Completed 200 OK in 78ms (Views: 0.7ms | ActiveRecord: 38.0ms | Allocations: 13609)
```

**Comment by Freika** [comment]
Hi @alex-phillips! What are you using to send the data to API endpoint? I see `created_at` attribute which should not be present when data comes from OwnTracks, and its presence prevents endpoint from accepting the data.

Also, for now please remove `?api_key=YOUR_API_KEY` from the URL, it's a bit early for that, I went ahead of myself exposing it in the interface 😅

**Comment by alex-phillips** [comment]
I'm using the Owntracks android app to send this data. Looking a the POST payload, it looks like owntracks adds that attribute in.

**Comment by Freika** [comment]
@alex-phillips in 0.1.6.3 release I removed filter on incoming params, can you try again with the updated version?

**Comment by alex-phillips** [comment]
Now I'm getting the following in the docker logs with the UI displaying the error below:

```
dawarich-app      | 12:07:33 css.1  | Rebuilding...
dawarich-app      | 12:07:33 css.1  | Error: Cannot find module 'daisyui'
dawarich-app      | 12:07:33 css.1  | Require stack:
dawarich-app      | 12:07:33 css.1  | - /var/app/config/tailwind.config.js
dawarich-app      | 12:07:33 css.1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
dawarich-app      | 12:07:33 css.1  |     at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
dawarich-app      | 12:07:33 css.1  |     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
dawarich-app      | 12:07:33 css.1  |     at Function.resolve (/snapshot/tailwindcss/standalone-cli/patch-require.js:34:38)
dawarich-app      | 12:07:33 css.1  |     at _resolve (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:250334)
dawarich-app      | 12:07:33 css.1  |     at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:252917)
dawarich-app      | 12:07:33 css.1  |     at /var/app/config/tailwind.config.js:17:5
dawarich-app      | 12:07:33 css.1  |     at evalModule (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:255614)
dawarich-app      | 12:07:33 css.1  |     at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
dawarich-app      | 12:07:33 css.1  |     at /snapshot/tailwindcss/lib/lib/load-config.js:48:30 {
dawarich-app      | 12:07:33 css.1  |   code: 'MODULE_NOT_FOUND',
dawarich-app      | 12:07:33 css.1  |   requireStack: [ '/var/app/config/tailwind.config.js' ]
dawarich-app      | 12:07:33 css.1  | }
```

![image](https://github.com/Freika/dawarich/assets/3135216/98f067f8-8d74-4321-8a7c-6b759ecdf824)

**Comment by Freika** [comment]
Let's follow this issue here: https://github.com/Freika/dawarich/issues/11
