### ISSUE TITLE
Export is failing

### ISSUE THREAD

**Issue by abmurksi** [Freika/dawarich#125]
**Describe the bug**
Export of points is failing. I select few points in the Points Tab, click Export. The export starts as background process but the status turns to failed and I can not export any data.

**Version**
0.9.1

**To Reproduce**
1. Go to 'Points'
2. Click on 'few points to select them'
3. Click 'Export points'
4. Wait
5. Reload tab to see error

**Expected behavior**
Status OK and a possibility to download the export/the points.

**Logs**
```
07:31:04 web.1  | D, [2024-07-16T07:31:04.428569 #56] DEBUG -- :   Export Create (3.1ms)  INSERT INTO "exports" ("name", "url", "status", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["name", "2024-06-16_2024-07-16"], ["url", nil], ["status", 0], ["user_id", 1], ["created_at", "2024-07-16 07:31:04.424516"], ["updated_at", "2024-07-16 07:31:04.424516"]]
07:31:04 web.1  | D, [2024-07-16T07:31:04.430202 #56] DEBUG -- :   ↳ app/controllers/exports_controller.rb:13:in `create'
07:31:04 web.1  | D, [2024-07-16T07:31:04.552695 #56] DEBUG -- :   TRANSACTION (122.1ms)  COMMIT
07:31:04 web.1  | D, [2024-07-16T07:31:04.553456 #56] DEBUG -- :   ↳ app/controllers/exports_controller.rb:13:in `create'
07:31:04 web.1  | I, [2024-07-16T07:31:04.554212 #56]  INFO -- : Enqueued ExportJob (Job ID: 250cdeed-941c-46e0-8db5-5c70e8adeccc) to Sidekiq(exports) with arguments: 3, "2024-06-16 00:00:00 +0200", "2024-07-16 23:59:59 +0200"
07:31:04 web.1  | I, [2024-07-16T07:31:04.555312 #56]  INFO -- : ↳ app/controllers/exports_controller.rb:15:in `create'
07:31:04 web.1  | I, [2024-07-16T07:31:04.555626 #56]  INFO -- : {"method":"POST","path":"/exports","format":"turbo_stream","controller":"ExportsController","action":"create","status":302,"allocations":3639,"duration":136.8,"view":0.0,"db":125.59,"location":"https://dawarich.mydomain.com/exports"}
07:31:04 web.1  | D, [2024-07-16T07:31:04.660278 #56] DEBUG -- :   User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
07:31:04 web.1  | D, [2024-07-16T07:31:04.660643 #56] DEBUG -- :   ↳ app/controllers/application_controller.rb:11:in `unread_notifications'
07:31:04 web.1  | D, [2024-07-16T07:31:04.661981 #56] DEBUG -- :   Rendering layout layouts/application.html.erb
07:31:04 web.1  | D, [2024-07-16T07:31:04.662046 #56] DEBUG -- :   Rendering exports/index.html.erb within layouts/application
07:31:04 web.1  | D, [2024-07-16T07:31:04.662841 #56] DEBUG -- :   Export Count (0.3ms)  SELECT COUNT(*) FROM "exports" WHERE "exports"."user_id" = $1  [["user_id", 1]]
07:31:04 web.1  | D, [2024-07-16T07:31:04.663235 #56] DEBUG -- :   ↳ app/views/exports/index.html.erb:9
07:31:04 web.1  | D, [2024-07-16T07:31:04.695659 #56] DEBUG -- :   Export Load (31.9ms)  SELECT "exports".* FROM "exports" WHERE "exports"."user_id" = $1 ORDER BY "exports"."created_at" DESC LIMIT $2 OFFSET $3  [["user_id", 1], ["LIMIT", 30], ["OFFSET", 0]]
07:31:04 web.1  | D, [2024-07-16T07:31:04.696010 #56] DEBUG -- :   ↳ app/views/exports/index.html.erb:32
07:31:04 web.1  | D, [2024-07-16T07:31:04.717370 #56] DEBUG -- :   Notification Load (0.3ms)  SELECT "notifications".* FROM "notifications" WHERE "notifications"."user_id" = $1 AND "notifications"."read_at" IS NULL  [["user_id", 1]]
07:31:04 web.1  | D, [2024-07-16T07:31:04.717916 #56] DEBUG -- :   ↳ app/views/shared/_navbar.html.erb:65
07:31:04 web.1  | I, [2024-07-16T07:31:04.720397 #56]  INFO -- : {"method":"GET","path":"/exports","format":"turbo_stream","controller":"ExportsController","action":"index","status":200,"allocations":15134,"duration":61.76,"view":25.97,"db":32.74}
07:31:37 web.1  | D, [2024-07-16T07:31:37.757246 #56] DEBUG -- :   User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
07:31:37 web.1  | D, [2024-07-16T07:31:37.758070 #56] DEBUG -- :   ↳ app/controllers/application_controller.rb:11:in `unread_notifications'
07:31:37 web.1  | D, [2024-07-16T07:31:37.759264 #56] DEBUG -- :   Rendering layout layouts/application.html.erb
07:31:37 web.1  | D, [2024-07-16T07:31:37.759318 #56] DEBUG -- :   Rendering exports/index.html.erb within layouts/application
07:31:37 web.1  | D, [2024-07-16T07:31:37.760217 #56] DEBUG -- :   Export Count (0.5ms)  SELECT COUNT(*) FROM "exports" WHERE "exports"."user_id" = $1  [["user_id", 1]]
07:31:37 web.1  | D, [2024-07-16T07:31:37.760976 #56] DEBUG -- :   ↳ app/views/exports/index.html.erb:9
07:31:37 web.1  | D, [2024-07-16T07:31:37.761712 #56] DEBUG -- :   Export Load (0.3ms)  SELECT "exports".* FROM "exports" WHERE "exports"."user_id" = $1 ORDER BY "exports"."created_at" DESC LIMIT $2 OFFSET $3  [["user_id", 1], ["LIMIT", 30], ["OFFSET", 0]]
07:31:37 web.1  | D, [2024-07-16T07:31:37.762029 #56] DEBUG -- :   ↳ app/views/exports/index.html.erb:32
07:31:37 web.1  | D, [2024-07-16T07:31:37.777125 #56] DEBUG -- :   Notification Load (0.3ms)  SELECT "notifications".* FROM "notifications" WHERE "notifications"."user_id" = $1 AND "notifications"."read_at" IS NULL  [["user_id", 1]]
07:31:37 web.1  | D, [2024-07-16T07:31:37.777590 #56] DEBUG -- :   ↳ app/views/shared/_navbar.html.erb:65
07:31:37 web.1  | I, [2024-07-16T07:31:37.779688 #56]  INFO -- : {"method":"GET","path":"/exports","format":"html","controller":"ExportsController","action":"index","status":200,"allocations":14998,"duration":23.74,"view":19.56,"db":1.22}
```

**Comment by Freika** [comment]
Can you provide logs from `dawarich_sidekiq` container?

**Comment by Freika** [comment]
@abmurksi thank you, it will be fixed in the next release
