### ISSUE TITLE
ERROR:  While executing gem ... (NoMethodError)

### ISSUE THREAD

**Issue by AdamSnow** [Freika/dawarich#132]
**Describe the bug**
Unable to access Dawarich app or Sidekiq. Dawarich_app crashes every few seconds.

**Version**
0.9.4

**Expected behavior**
Dawarich to load.

**Logs**
dawarich_app:

```
Environment: development
dawarich_db (172.18.0.4:5432) open
ERROR:  Loading command: update (LoadError)
	cannot load such file -- /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/vendored_optparse
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:9:in `require_relative'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:9:in `<top (required)>'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/commands/update_command.rb:3:in `require_relative'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/commands/update_command.rb:3:in `<top (required)>'
	<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:236:in `load_and_instantiate'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:137:in `[]'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:209:in `find_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:251:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `deprecated?' for nil:NilClass

    cmd.deprecation_warning if cmd.deprecated?
                                  ^^^^^^^^^^^^
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'

Environment: development
nc: bad address 'dawarich_db'
Waiting for PostgreSQL to be ready...
```

dawarich_db:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-07-24 18:33:58.479 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
2024-07-24 18:33:58.479 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-24 18:33:58.479 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-07-24 18:33:58.482 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-24 18:33:58.487 UTC [21] LOG:  database system was shut down at 2024-07-24 18:27:23 UTC
2024-07-24 18:33:58.490 UTC [1] LOG:  database system is ready to accept connections
2024-07-24 18:34:03.177 UTC [34] ERROR:  database "dawarich_development" already exists
2024-07-24 18:34:03.177 UTC [34] STATEMENT:  CREATE DATABASE "dawarich_development" ENCODING = 'unicode'
2024-07-24 18:34:03.202 UTC [35] ERROR:  database "dawarich_test" already exists
2024-07-24 18:34:03.202 UTC [35] STATEMENT:  CREATE DATABASE "dawarich_test" ENCODING = 'unicode'

```
**Additional context**

**Comment by sfwr** [comment]
Same.

Running on docker-compose.

**Comment by Freika** [comment]
This happens from time to time and I haven't found the reason yet, but restarting the container usually helps. I'll keep my eye on this one though

**Comment by AdamSnow** [comment]
I've not been successful with restarting. I've reinstalled Ruby, am considering reinstalling completely but was hoping not to lose my database.

**Comment by Freika** [comment]
Reinstalling ruby? I'm not sure what you mean by that, are you running Dawarich in Docker? If yes, why would you need to reinstall ruby?

**Comment by AdamSnow** [comment]
The research I had done indicated a problem with Ruby or configuration, so was just attempting to resolve it - Glad to know that wasn't required! yes, running within Docker. I've restarted everything probably 100 times over the past week trying to get it going, no change.

**Comment by AdamSnow** [comment]
Upgrading to 0.9.8 got me back up and running!
