### ISSUE TITLE
WARN: Errno::EADDRNOTAVAIL: Failed to open TCP connection to nominatim.openstreetmap.org:443 (Address not available - connect(2) for "nominatim.openstreetmap.org" port 443

### ISSUE THREAD

**Issue by sfwr** [Freika/dawarich#141]
**Describe the bug**
when importing GPX with ~2000 points, this consistently fails after ~600 points

**Version**
0.9.7

**Logs**
```
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:77:in `block in wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:74:in `wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:28:in `execute'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:70:in `perform'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:210:in `execute_job'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:180:in `traverse'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/metrics/tracking.rb:26:in `track'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/metrics/tracking.rb:126:in `call'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:173:in `invoke'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_retry.rb:113:in `local'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/rails.rb:16:in `block in call'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:77:in `block in wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:74:in `wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/rails.rb:15:in `call'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:271:in `stats'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_logger.rb:13:in `call'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_retry.rb:80:in `global'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:128:in `block in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_logger.rb:39:in `prepare'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:127:in `dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:177:in `handle_interrupt'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:177:in `block in process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:176:in `handle_interrupt'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:176:in `process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:82:in `process_one'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:72:in `run'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/component.rb:10:in `watchdog'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/component.rb:19:in `block in safe_thread'
2024-07-27T13:50:16.159Z pid=54 tid=1dja class=ReverseGeocodingJob jid=a5e9fa655e5d4156c64055c5 elapsed=1.151 INFO: fail
2024-07-27T13:50:16.159Z pid=54 tid=1dja WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"reverse_geocoding","wrapped":"ReverseGeocodingJob","args":[{"job_class":"ReverseGeocodingJob","job_id":"fa346120-33f3-4f81-b551-90e49f821c85","provider_job_id":null,"queue_name":"reverse_geocoding","priority":null,"arguments":[12678],"executions":0,"exception_executions":{},"locale":"en","timezone":"America/Toronto","enqueued_at":"2024-07-27T13:47:11.106017330Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"a5e9fa655e5d4156c64055c5","created_at":1722088031.1061175,"enqueued_at":1722088031.1062}}
2024-07-27T13:50:16.160Z pid=54 tid=1dja WARN: Errno::EADDRNOTAVAIL: Failed to open TCP connection to nominatim.openstreetmap.org:443 (Address not available - connect(2) for "nominatim.openstreetmap.org" port 443)
2024-07-27T13:50:16.161Z pid=54 tid=1dja WARN: app/services/reverse_geocoding/fetch_data.rb:15:in `call'
app/jobs/reverse_geocoding_job.rb:9:in `perform'
2024-07-27T13:50:16.161Z pid=54 tid=1do6 class=ReverseGeocodingJob jid=6889709637833fb8be21f927 INFO: start
I, [2024-07-27T13:50:16.166470 #54]  INFO -- : Performing ReverseGeocodingJob (Job ID: aef7b811-19a3-4661-8366-2c662e44a5dc) from Sidekiq(reverse_geocoding) enqueued at 2024-07-27T13:47:11.142081364Z with arguments: 12681
D, [2024-07-27T13:50:16.168406 #54] DEBUG -- :   Point Load (0.5ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 12681], ["LIMIT", 1]]
D, [2024-07-27T13:50:16.168846 #54] DEBUG -- :   ↳ app/services/reverse_geocoding/fetch_data.rb:7:in `initialize'
Geocoding API not responding fast enough (use Geocoder.configure(:timeout => ...) to set limit).
I, [2024-07-27T13:50:17.064304 #54]  INFO -- : Performed ReverseGeocodingJob (Job ID: 154fe8cf-0fad-40a0-a1d6-e7745b551fc9) from Sidekiq(reverse_geocoding) in 3006.45ms
2024-07-27T13:50:17.067Z pid=54 tid=1dhy class=ReverseGeocodingJob jid=28320c2b1cb83111a3aca9a9 elapsed=3.018 INFO: done
2024-07-27T13:50:17.067Z pid=54 tid=1dhy class=ReverseGeocodingJob jid=b3dea64eebaed894a35e0118 INFO: start
I, [2024-07-27T13:50:17.073948 #54]  INFO -- : Performing ReverseGeocodingJob (Job ID: 81f22c4e-b8d1-44ee-a29e-c188fd8597c2) from Sidekiq(reverse_geocoding) enqueued at 2024-07-27T13:47:11.159894427Z with arguments: 12682
D, [2024-07-27T13:50:17.075904 #54] DEBUG -- :   Point Load (0.5ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 12682], ["LIMIT", 1]]
D, [2024-07-27T13:50:17.076376 #54] DEBUG -- :   ↳ app/services/reverse_geocoding/fetch_data.rb:7:in `initialize'
E, [2024-07-27T13:50:17.182126 #54] ERROR -- : Error performing ReverseGeocodingJob (Job ID: 81f22c4e-b8d1-44ee-a29e-c188fd8597c2) from Sidekiq(reverse_geocoding) in 108.14ms: Errno::EADDRNOTAVAIL (Failed to open TCP connection to nominatim.openstreetmap.org:443 (Address not available - connect(2) for "nominatim.openstreetmap.org" port 443)):
/usr/local/lib/ruby/3.2.0/net/http.rb:1603:in `initialize'
/usr/local/lib/ruby/3.2.0/net/http.rb:1603:in `open'
/usr/local/lib/ruby/3.2.0/net/http.rb:1603:in `block in connect'
/var/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
/var/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.4.1/lib/timeout.rb:193:in `timeout'
/usr/local/lib/ruby/3.2.0/net/http.rb:1601:in `connect'
/usr/local/lib/ruby/3.2.0/net/http.rb:1580:in `do_start'
/usr/local/lib/ruby/3.2.0/net/http.rb:1569:in `start'
/usr/local/lib/ruby/3.2.0/net/http.rb:1029:in `start'
/var/app/vendor/bundle/ruby/3.2.0/gems/geocoder-1.8.3/lib/geocoder/lookups/base.rb:300:in `make_api_request'
/var/app/vendor/bundle/ruby/3.2.0/gems/geocoder-1.8.3/lib/geocoder/lookups/base.rb:250:in `fetch_raw_data'
/var/app/vendor/bundle/ruby/3.2.0/gems/geocoder-1.8.3/lib/geocoder/lookups/base.rb:196:in `fetch_data'
/var/app/vendor/bundle/ruby/3.2.0/gems/geocoder-1.8.3/lib/geocoder/lookups/nominatim.rb:36:in `results'
/var/app/vendor/bundle/ruby/3.2.0/gems/geocoder-1.8.3/lib/geocoder/lookups/base.rb:46:in `search'
/var/app/vendor/bundle/ruby/3.2.0/gems/geocoder-1.8.3/lib/geocoder/query.rb:11:in `execute'
/var/app/vendor/bundle/ruby/3.2.0/gems/geocoder-1.8.3/lib/geocoder.rb:22:in `search'
/var/app/app/services/reverse_geocoding/fetch_data.rb:15:in `call'
/var/app/app/jobs/reverse_geocoding_job.rb:9:in `perform'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:69:in `block in _perform_job'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:68:in `_perform_job'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:32:in `_perform_job'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:52:in `perform_now'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:40:in `block in instrument'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `block in instrument'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `instrument'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:39:in `instrument'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:11:in `instrument'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:26:in `perform_now'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:18:in `block in perform_now'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:27:in `tag_logger'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:18:in `perform_now'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:30:in `block in execute'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:77:in `block in wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:74:in `wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:28:in `execute'
/var/app/vendor/bundle/ruby/3.2.0/gems/activejob-7.1.3.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:70:in `perform'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:210:in `execute_job'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:180:in `traverse'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/metrics/tracking.rb:26:in `track'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/metrics/tracking.rb:126:in `call'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:173:in `invoke'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_retry.rb:113:in `local'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/rails.rb:16:in `block in call'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:77:in `block in wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:74:in `wrap'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/rails.rb:15:in `call'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:271:in `stats'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_logger.rb:13:in `call'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_retry.rb:80:in `global'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:128:in `block in dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_logger.rb:39:in `prepare'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:127:in `dispatch'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:177:in `handle_interrupt'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:177:in `block in process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:176:in `handle_interrupt'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:176:in `process'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:82:in `process_one'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:72:in `run'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/component.rb:10:in `watchdog'
/var/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/component.rb:19:in `block in safe_thread'
2024-07-27T13:50:17.186Z pid=54 tid=1dhy class=ReverseGeocodingJob jid=b3dea64eebaed894a35e0118 elapsed=0.118 INFO: fail
2024-07-27T13:50:17.186Z pid=54 tid=1dhy WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"reverse_geocoding","wrapped":"ReverseGeocodingJob","args":[{"job_class":"ReverseGeocodingJob","job_id":"81f22c4e-b8d1-44ee-a29e-c188fd8597c2","provider_job_id":null,"queue_name":"reverse_geocoding","priority":null,"arguments":[12682],"executions":0,"exception_executions":{},"locale":"en","timezone":"America/Toronto","enqueued_at":"2024-07-27T13:47:11.159894427Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"b3dea64eebaed894a35e0118","created_at":1722088031.1605456,"enqueued_at":1722088031.1606326}}
2024-07-27T13:50:17.186Z pid=54 tid=1dhy WARN: Errno::EADDRNOTAVAIL: Failed to open TCP connection to nominatim.openstreetmap.org:443 (Address not available - connect(2) for "nominatim.openstreetmap.org" port 443)
2024-07-27T13:50:17.187Z pid=54 tid=1dhy WARN: app/services/reverse_geocoding/fetch_data.rb:15:in `call'
app/jobs/reverse_geocoding_job.rb:9:in `perform'
2024-07-27T13:50:17.187Z pid=54 tid=1dpi class=ReverseGeocodingJob jid=677f7e6afd8d7435e3238680 INFO: start
I, [2024-07-27T13:50:17.196885 #54]  INFO -- : Performing ReverseGeocodingJob (Job ID: 5579ebd6-ee05-4a25-a2e5-050a76fc7d3c) from Sidekiq(reverse_geocoding) enqueued at 2024-07-27T13:47:11.169842861Z with arguments: 12683
D, [2024-07-27T13:50:17.199015 #54] DEBUG -- :   Point Load (0.4ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 12683], ["LIMIT", 1]]
D, [2024-07-27T13:50:17.199675 #54] DEBUG -- :   ↳ app/services/reverse_geocoding/fetch_data.rb:7:in `initialize'
Geocoding API not responding fast enough (use Geocoder.configure(:timeout => ...) to set limit).
I, [2024-07-27T13:50:17.517944 #54]  INFO -- : Performed ReverseGeocodingJob (Job ID: fbb70215-819e-40a5-b1b2-bae53ec77647) from Sidekiq(reverse_geocoding) in 3005.48ms
2024-07-27T13:50:17.519Z pid=54 tid=1dae class=ReverseGeocodingJob jid=2b8d51cc68852e4a87f7f079 elapsed=3.015 INFO: done
2024-07-27T13:50:17.520Z pid=54 tid=1dae class=ReverseGeocodingJob jid=04e418a13b114d29772df8a5 INFO: start
I, [2024-07-27T13:50:17.525652 #54]  INFO -- : Performing ReverseGeocodingJob (Job ID: 36707499-dcb4-4926-8462-bf1b67c21125) from Sidekiq(reverse_geocoding) enqueued at 2024-07-27T13:47:11.187303431Z with arguments: 12684
D, [2024-07-27T13:50:17.527666 #54] DEBUG -- :   Point Load (0.4ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 12684], ["LIMIT", 1]]
D, [2024-07-27T13:50:17.528729 #54] DEBUG -- :   ↳ app/services/reverse_geocoding/fetch_data.rb:7:in `initialize'
```

Running via docker-compose on an unraid server.

**Comment by Freika** [comment]
> Errno::EADDRNOTAVAIL: Failed to open TCP connection to nominatim.openstreetmap.org:443 (Address not available - connect(2) for "nominatim.openstreetmap.org" port 443)

As we can see here, Nominatim doesn't return a valid response. It might be problems with network or a temp ban from Nominatim's side if your app sends too many requests in a short time. Nominatim itself asks their users to limit their request to 1 per second.

**Comment by sfwr** [comment]
Hmmm,  I just tried a request to

https://nominatim.openstreetmap.org/search?format=json&limit=3&q=toronto

which doesn't work on my desktop, but works over a cell connection (with presumably a different ip address), so it does sount like I've been blocked by nominatim.

This seems to be the result of running an import on the default settings in the docker-compose file though which seems like an undesired result of running dawarich.

I'll wait to be unbanned and see if having my concurrency set to 1 now instead of 10 will do anything.

**Comment by sfwr** [comment]
Can confirm I got unblocked today, and running it with a concurrency of 1 is not causing be to be blocked again.

However, I'm seeing this now

```D, [2024-07-28T13:08:51.993966 #54] DEBUG -- :   ↳ app/services/reverse_geocoding/fetch_data.rb:7:in `initialize'
Geocoding API's response was not valid JSON```


```
D, [2024-07-28T13:09:10.024284 #54] DEBUG -- :   Point Load (0.4ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 16136], ["LIMIT", 1]]
D, [2024-07-28T13:09:10.024845 #54] DEBUG -- :   ↳ app/services/reverse_geocoding/fetch_data.rb:7:in `initialize'
Geocoding API's response was not valid JSON
I, [2024-07-28T13:09:13.015666 #54]  INFO -- : Performed ReverseGeocodingJob (Job ID: 1b94b375-a4f0-419d-8e7c-8fe9cd92a3a7) from Sidekiq(reverse_geocoding) in 2994.17ms
2024-07-28T13:09:13.017Z pid=54 tid=c2le class=ReverseGeocodingJob jid=863d597118b9785aff69a0d0 elapsed=3.002 INFO: done
2024-07-28T13:09:13.018Z pid=54 tid=c2le class=ReverseGeocodingJob jid=6e5270e2d5c5e1c76ec8f633 INFO: start
I, [2024-07-28T13:09:13.025454 #54]  INFO -- : Performing ReverseGeocodingJob (Job ID: be949a09-e54f-41e7-8b46-959121072486) from Sidekiq(reverse_geocoding) enqueued at 2024-07-28T13:02:15.618531550Z with arguments: 16137
D, [2024-07-28T13:09:13.027505 #54] DEBUG -- :   Point Load (0.5ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 16137], ["LIMIT", 1]]
D, [2024-07-28T13:09:13.028649 #54] DEBUG -- :   ↳ app/services/reverse_geocoding/fetch_data.rb:7:in `initialize'
Geocoding API's response was not valid JSON
I, [2024-07-28T13:09:16.022144 #54]  INFO -- : Performed ReverseGeocodingJob (Job ID: be949a09-e54f-41e7-8b46-959121072486) from Sidekiq(reverse_geocoding) in 2996.72ms
2024-07-28T13:09:16.024Z pid=54 tid=c2le class=ReverseGeocodingJob jid=6e5270e2d5c5e1c76ec8f633 elapsed=3.006 INFO: done
2024-07-28T13:09:16.024Z pid=54 tid=c2le class=ReverseGeocodingJob jid=d047aa4c8cf9eed516e8942d INFO: start
I, [2024-07-28T13:09:16.033703 #54]  INFO -- : Performing ReverseGeocodingJob (Job ID: 1c9c3621-8726-4129-be60-4700ee9f0ca3) from Sidekiq(reverse_geocoding) enqueued at 2024-07-28T13:02:15.639678494Z with arguments: 16138
D, [2024-07-28T13:09:16.036370 #54] DEBUG -- :   Point Load (0.4ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 16138], ["LIMIT", 1]]
D, [2024-07-28T13:09:16.036959 #54] DEBUG -- :   ↳ app/services/reverse_geocoding/fetch_data.rb:7:in `initialize'
```

**Comment by HStep20** [comment]
I am seeing similar results. Initially it was the EADDRNOTAVAIL error, but after reducing the concurrency to 1, Its claiming the json is not valid

**Comment by Freika** [comment]
It's still a problem with Nominatim response, probably, rate limiting: https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md#nominatim-nominatim
