### ISSUE TITLE
Unable to start on Synology with docker-cmpose

### ISSUE THREAD

**Issue by alexkutsan** [Freika/dawarich#159]
**Describe the bug**
Try to startup app with docker-compose on Synology.
But failed on very beginning. 

**Version**

dawarich version 0.9.9 (latest docker image)
Sunology version:
```
alex@AlexNAS:~/Drive/services/darwarich$ uname  -a
Linux AlexNAS 3.10.105 #25556 SMP Sat Aug 28 02:13:34 CST 2021 x86_64 GNU/Linux synology_braswell_216+II
```

**To Reproduce**

1. wget https://raw.githubusercontent.com/Freika/dawarich/master/docker-compose.yml 
2. docker-compose up

**Expected behavior**
Server start succesfuly

**Logs**
```
dawarich_app      | bin/rails aborted!
dawarich_app      | failed to get urandom
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/loader/config.rb:89:in `initialize'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/loader.rb:101:in `initialize'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/gem_loader.rb:20:in `initialize'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/gem_loader.rb:15:in `new'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/gem_loader.rb:15:in `__new'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/registry.rb:90:in `loader_for_gem'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/loader.rb:374:in `for_gem'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/actioncable-7.1.3.4/lib/action_cable.rb:30:in `<main>'
dawarich_app      | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_app      | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/actioncable-7.1.3.4/lib/action_cable/engine.rb:4:in `<main>'
dawarich_app      | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_app      | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/all.rb:20:in `block in <main>'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/all.rb:18:in `each'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/all.rb:18:in `<main>'
dawarich_app      | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_app      | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
dawarich_app      | /var/app/config/application.rb:5:in `<main>'
dawarich_app      | /var/app/Rakefile:6:in `require_relative'
dawarich_app      | /var/app/Rakefile:6:in `<main>'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/command.rb:156:in `invoke_rake'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/command.rb:73:in `block in invoke'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<main>'
dawarich_app      | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_app      | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_app      | /var/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
dawarich_app      | bin/rails:4:in `<main>'
dawarich_app      | (See full trace by running task with --trace)
dawarich_app      | Latest version already installed. Done.
dawarich_sidekiq  | bin/rails aborted!
dawarich_sidekiq  | failed to get urandom
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/loader/config.rb:89:in `initialize'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/loader.rb:101:in `initialize'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/gem_loader.rb:20:in `initialize'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/gem_loader.rb:15:in `new'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/gem_loader.rb:15:in `__new'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/registry.rb:90:in `loader_for_gem'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/loader.rb:374:in `for_gem'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/actioncable-7.1.3.4/lib/action_cable.rb:30:in `<main>'
dawarich_sidekiq  | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_sidekiq  | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/actioncable-7.1.3.4/lib/action_cable/engine.rb:4:in `<main>'
dawarich_sidekiq  | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_sidekiq  | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/all.rb:20:in `block in <main>'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/all.rb:18:in `each'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/all.rb:18:in `<main>'
dawarich_sidekiq  | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_sidekiq  | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
dawarich_sidekiq  | /var/app/config/application.rb:5:in `<main>'
dawarich_sidekiq  | /var/app/Rakefile:6:in `require_relative'
dawarich_sidekiq  | /var/app/Rakefile:6:in `<main>'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/command.rb:156:in `invoke_rake'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/command.rb:73:in `block in invoke'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<main>'
dawarich_sidekiq  | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_sidekiq  | <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
dawarich_sidekiq  | bin/rails:4:in `<main>'
dawarich_sidekiq  | (See full trace by running task with --trace)
```

**Comment by overdarki** [comment]
There is a specific docker-compose file for synology devices, you can find more information here
[https://github.com/Freika/dawarich/blob/master/docs/How_to_install_Dawarich_on_Synology.md](url)

**Comment by Freika** [comment]
Should be fixed in https://github.com/Freika/dawarich/releases/tag/0.15.7
