### ISSUE TITLE
Dawarich does not start if internet is blocked to the container.

### ISSUE THREAD

**Issue by SayantanRC** [Freika/dawarich#188]
**Describe the bug**
I use iptables to block internet access to most of my containers. If I block internet access to Dawarich during startup, it just fails at Ruby gems update.

**Version**
Include version of Dawarich you're experiencing problem on.

**To Reproduce**
1. Block dawarich container's internet access during startup with this command:
   ```
   sudo iptables -I DOCKER-USER -d $container_ip -o eth0 -j DROP && sudo iptables -I DOCKER-USER -s $container_ip -o eth0 -j DROP
   ```
2. Check the logs.

**Expected behavior**
Dawarich should start even if it cannot check for updates.

**Logs**
```
Environment: development
dawarich_db (172.27.0.3:5432) open
Updating rubygems-update
Fetching rubygems-update-3.5.7.gem
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ apply2files - /usr/local/bundle/gems/rubygems-update-3.5.7/MAINTAINERS.txt
	/usr/local/lib/ruby/3.2.0/fileutils.rb:2222:in `chmod'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:2222:in `chmod'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1820:in `block in chmod'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1819:in `each'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1819:in `chmod'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:450:in `block (2 levels) in extract_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:61:in `each'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:416:in `block in extract_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:542:in `block in open_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:539:in `wrap'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:539:in `open_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:415:in `extract_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:393:in `block (2 levels) in extract_files'
	/usr/local/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:61:in `each'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:390:in `block in extract_files'
	/usr/local/lib/ruby/3.2.0/rubygems/package/file_source.rb:30:in `open'
	/usr/local/lib/ruby/3.2.0/rubygems/package/file_source.rb:30:in `with_read_io'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:387:in `extract_files'
	/usr/local/lib/ruby/3.2.0/rubygems/installer.rb:855:in `extract_files'
	/usr/local/lib/ruby/3.2.0/rubygems/installer.rb:325:in `install'
	/usr/local/lib/ruby/3.2.0/rubygems/resolver/specification.rb:105:in `install'
	/usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:195:in `block in install'
	/usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:183:in `each'
	/usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:183:in `install'
	/usr/local/lib/ruby/3.2.0/rubygems/dependency_installer.rb:253:in `install'
	/usr/local/lib/ruby/3.2.0/rubygems/commands/update_command.rb:247:in `update_gem'
	/usr/local/lib/ruby/3.2.0/rubygems/commands/update_command.rb:283:in `update_rubygems'
	/usr/local/lib/ruby/3.2.0/rubygems/commands/update_command.rb:99:in `execute'
	/usr/local/lib/ruby/3.2.0/rubygems/command.rb:328:in `invoke_with_build_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:253:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'
Environment: development
dawarich_db (172.27.0.3:5432) open
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	Unable to resolve dependency: user requested 'rubygems-update (= 3.5.7)'
ERROR:  Could not find a valid gem 'bundler' (= 2.5.9), here is why:
          Unable to download data from https://rubygems.org/ - Net::OpenTimeout: Failed to open TCP connection to rubygems.org:443 (execution expired) (https://rubygems.org/specs.4.8.gz)
```

**Comment by Freika** [comment]
Dawarich is not an offline-first application: it has to install dependencies (although it will be removed in the future as everything should be already present in the docker image), and it also relies on CDNs for some js code and on tiling services to render the map. So, at this point this is not considered a bug.

**Comment by SayantanRC** [comment]
Ok so at the moment I am directly using owntrack's recorder and frontend. @Freika Will there be any option in the future to import the data from owntrack recorder to dawarich?

**Comment by Freika** [comment]
@SayantanRC yes, it's already implemented: https://dawarich.app/docs/tutorials/import-existing-data#owntracks-and-dawarich

**Comment by SayantanRC** [comment]
Thank you so much

**Comment by SayantanRC** [comment]
@Freika according to the import options from Owntracks, I should get a download button on the web interface. But I don't see any.

![image](https://github.com/user-attachments/assets/8194fd31-b169-40bc-9d8d-ecf4d7e4c9a5)

Could you let me know what I am doing wrong?

**Comment by Freika** [comment]
@SayantanRC in the frontend app, there used to be the "Download" button, like on this screenshot:

<img width="123" alt="изображение" src="https://github.com/user-attachments/assets/c11a469d-77f4-4eb3-9f1f-6dcf0e44963c">

I just updated my Owntracks server app and it seems like the button is gone. You can do the following:

1. Go to `volumes/owntracks-recorder/store/rec/user/topic`
2. There you'll find `.rec` files
3. Rename them to have `.json` extension
4. Import them to Dawarich

That should work.

**Comment by SayantanRC** [comment]
@Freika I forgot to comment. No unfortunately the `.rec` file does not store lines as json. Here are two lines for example.
```
2024-08-30T15:56:41Z	*                 	{"_type":"location","BSSID":"xx:xx:xx:xx:xx:xx","SSID":"XXXXXXXX","_id":"8e3e63a3","acc":39,"alt":740,"batt":42,"bs":1,"conn":"w","created_at":1725033401,"lat":xx.xxxxxx,"lon":xx.xxxxxx,"m":1,"tid":"go","topic":"owntracks/user/sargo","tst":1725033401,"vac":48,"vel":1,"_http":true}
2024-08-30T15:57:40Z	*                 	{"_type":"location","BSSID":"xx:xx:xx:xx:xx:xx","SSID":"XXXXXXXX","_id":"eae1ba4b","acc":32,"alt":771,"batt":41,"bs":1,"conn":"w","created_at":1725033460,"lat":xx.xxxxxx,"lon":xx.xxxxxx,"m":1,"tid":"go","topic":"owntracks/user/sargo","tst":1725033460,"vac":32,"vel":0,"_http":true}
```
(Values redacted)  

Changing the extension will just throw an error while importing.

**Comment by SayantanRC** [comment]
I made this script using chatgpt and some modifications to convert `.rec` files to `.gpx` files. This does not hundred percent work, as I don't get battery and velocity information on dawarich. But it is something.

```python3
import json
import xml.etree.ElementTree as ET
from xml.dom import minidom

def rec_to_gpx(input_file, output_file):
    # Create the GPX root element
    gpx = ET.Element(
        'gpx', 
        version='1.1',
        creator='OwnTracks Export',
        xmlns='http://www.topografix.com/GPX/1/1',
    )
    trk = ET.SubElement(gpx, 'trk')
    trkseg = ET.SubElement(trk, 'trkseg')

    count = 0

    # Read the .rec file
    with open(input_file, 'r') as infile:
        for line in infile:
            parts = line.strip().split('\t')
            if len(parts) == 3:
                json_str = parts[2]
                timestamp = parts[0].strip()
                try:
                    point_data = json.loads(json_str)

                    # Create a GPX trackpoint element
                    trkpt = ET.SubElement(trkseg, 'trkpt', lat=str(point_data.get('lat')), lon=str(point_data.get('lon')))
                    
                    # Time is apparently mandatory.
                    ET.SubElement(trkpt, 'time').text = timestamp

                    # Add optional elements
                    if 'alt' in point_data:
                        ET.SubElement(trkpt, 'ele').text = str(point_data['alt'])
                    if 'batt' in point_data:
                        ET.SubElement(trkpt, 'battery').text = str(point_data['batt'])
                    if 'vel' in point_data:
                        ET.SubElement(trkpt, 'speed').text = str(point_data['vel'])

                    count = count + 1

                except json.JSONDecodeError:
                    print(f"Error decoding JSON: {json_str}")

    # Convert the ElementTree to a string
    xml_str = ET.tostring(gpx, encoding='utf-8')

    # Beautify the XML string
    pretty_xml_str = minidom.parseString(xml_str).toprettyxml(indent="  ")

    # Write the beautified XML to the output file
    with open(output_file, 'w') as outfile:
        outfile.write(pretty_xml_str)

    print(f"Data successfully converted and saved to {output_file}. Points: {count}")

# Usage
input_file = 'file.rec'
output_file = 'file.gpx'
rec_to_gpx(input_file, output_file)
```

**Comment by Freika** [comment]
@SayantanRC neat! I think I'll just implement importing .rec files from Owntracks in Dawarich and that will close the question to its end :)
