### ISSUE TITLE
Launching app causes error when updating gems

### ISSUE THREAD

**Issue by Aikufurr** [Freika/dawarich#19]
Docker version: [0.1.7.3](https://hub.docker.com/layers/freikin/dawarich/0.1.7.3/images/sha256-140bc3d3de90f68d13b521715aa209f51e161b2fa0a20069a81cae3ee0137d8e?context=explore)
OS: Ubuntu 22.04.4 LTS aarch64
Kernel: 5.15.0-101-generic
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
   
Logs from `dawarich_app`
```
Environment: development
dawarich_db (192.168.48.2:5432) open
Updating rubygems-update
Fetching rubygems-update-3.5.7.gem
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ apply2files - /usr/local/bundle/gems/rubygems-update-3.5.7/bundler/lib/bundler/templates/newgem/test/minitest/test_helper.rb.tt
	/usr/local/lib/ruby/3.2.0/fileutils.rb:2222:in `chmod'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:2222:in `chmod'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1820:in `block in chmod'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1819:in `each'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1819:in `chmod'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:450:in `block (2 levels) in extract_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:61:in `each'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:416:in `block in extract_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:542:in `block in open_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:539:in `wrap'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:539:in `open_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:415:in `extract_tar_gz'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:393:in `block (2 levels) in extract_files'
	/usr/local/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:61:in `each'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:390:in `block in extract_files'
	/usr/local/lib/ruby/3.2.0/rubygems/package/file_source.rb:30:in `open'
	/usr/local/lib/ruby/3.2.0/rubygems/package/file_source.rb:30:in `with_read_io'
	/usr/local/lib/ruby/3.2.0/rubygems/package.rb:387:in `extract_files'
	/usr/local/lib/ruby/3.2.0/rubygems/installer.rb:855:in `extract_files'
	/usr/local/lib/ruby/3.2.0/rubygems/installer.rb:325:in `install'
	/usr/local/lib/ruby/3.2.0/rubygems/resolver/specification.rb:105:in `install'
	/usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:195:in `block in install'
	/usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:183:in `each'
	/usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:183:in `install'
	/usr/local/lib/ruby/3.2.0/rubygems/dependency_installer.rb:253:in `install'
	/usr/local/lib/ruby/3.2.0/rubygems/commands/update_command.rb:247:in `update_gem'
	/usr/local/lib/ruby/3.2.0/rubygems/commands/update_command.rb:283:in `update_rubygems'
	/usr/local/lib/ruby/3.2.0/rubygems/commands/update_command.rb:99:in `execute'
	/usr/local/lib/ruby/3.2.0/rubygems/command.rb:328:in `invoke_with_build_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:253:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'
```

**Comment by Freika** [comment]
@Aikufurr is this still a problem or can we close it?

**Comment by Aikufurr** [comment]
@Freika all services are up and running fine with errors, thanks for the ongoing support!
