### ISSUE TITLE
Can't upgrade from 0.9.11 to 0.9.12 and newer

### ISSUE THREAD

**Issue by rheicide** [Freika/dawarich#191]
**Describe the bug**
Data migrations fail when upgrading to 0.9.12 and newer versions.

**Version**
0.9.11

**To Reproduce**
1. Change image version of app and sidekick to 0.9.12 in `compose.yml`
2. `docker compose up -d`
3. See errors in logs

**Logs**
```
...
D, [2024-08-22T08:28:26.959234 #42] DEBUG -- :   [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
D, [2024-08-22T08:28:26.966487 #42] DEBUG -- :   [1m[36mPoint Update (2.0ms)[0m  [1m[33mUPDATE "points" SET "battery_status" = $1, "battery" = $2, "altitude" = $3, "velocity" = $4, "trigger" = $5, "connection" = $6, "vertical_accuracy" = $7, "accuracy" = $8, "inrids" = $9, "in_regions" = $10, "updated_at" = $11 WHERE "points"."id" = $12[0m  [["battery_status", 1], ["battery", 84], ["altitude", -9], ["velocity", "0"], ["trigger", 1], ["connection", 0], ["vertical_accuracy", 5], ["accuracy", 2200], ["inrids", nil], ["in_regions", nil], ["updated_at", "2024-08-22 08:28:26.962594"], ["id", 1201]]
D, [2024-08-22T08:28:26.971891 #42] DEBUG -- :   [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
D, [2024-08-22T08:28:26.979253 #42] DEBUG -- :   [1m[36mPoint Update (1.8ms)[0m  [1m[33mUPDATE "points" SET "battery_status" = $1, "battery" = $2, "altitude" = $3, "velocity" = $4, "trigger" = $5, "connection" = $6, "vertical_accuracy" = $7, "accuracy" = $8, "inrids" = $9, "in_regions" = $10, "updated_at" = $11 WHERE "points"."id" = $12[0m  [["battery_status", 1], ["battery", 75], ["altitude", -1], ["velocity", "0"], ["trigger", 0], ["connection", 0], ["vertical_accuracy", 1], ["accuracy", 20], ["inrids", nil], ["in_regions", nil], ["updated_at", "2024-08-22 08:28:26.975527"], ["id", 1206]]
D, [2024-08-22T08:28:26.984873 #42] DEBUG -- :   [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
D, [2024-08-22T08:28:26.990245 #42] DEBUG -- :   [1m[36mPoint Update (1.0ms)[0m  [1m[33mUPDATE "points" SET "battery_status" = $1, "battery" = $2, "altitude" = $3, "velocity" = $4, "trigger" = $5, "connection" = $6, "vertical_accuracy" = $7, "accuracy" = $8, "inrids" = $9, "in_regions" = $10, "updated_at" = $11 WHERE "points"."id" = $12[0m  [["battery_status", 1], ["battery", 67], ["altitude", 7], ["velocity", "45"], ["trigger", 0], ["connection", 0], ["vertical_accuracy", 3], ["accuracy", 4], ["inrids", nil], ["in_regions", nil], ["updated_at", "2024-08-22 08:28:26.987775"], ["id", 1211]]
I, [2024-08-22T08:28:26.992424 #42]  INFO -- : 1381 points updated from owntracks imports
D, [2024-08-22T08:28:27.035341 #42] DEBUG -- :   [1m[36mPoint Count (42.0ms)[0m  [1m[34mSELECT COUNT(*) FROM "points" WHERE (raw_data -> 'm' is not null and raw_data -> 'acc' is not null)[0m
I, [2024-08-22T08:28:27.036948 #42]  INFO -- : Updating 18770 points
D, [2024-08-22T08:28:27.338223 #42] DEBUG -- :   [1m[36mPoint Load (293.7ms)[0m  [1m[34mSELECT "points".* FROM "points" WHERE (raw_data -> 'm' is not null and raw_data -> 'acc' is not null)[0m
D, [2024-08-22T08:28:28.148682 #42] DEBUG -- :   [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
D, [2024-08-22T08:28:28.154984 #42] DEBUG -- :   [1m[36mPoint Update (1.3ms)[0m  [1m[33mUPDATE "points" SET "battery_status" = $1, "updated_at" = $2 WHERE "points"."id" = $3[0m  [["battery_status", 1], ["updated_at", "2024-08-22 08:28:28.152373"], ["id", 15721]]
D, [2024-08-22T08:28:28.168074 #42] DEBUG -- :   [1m[36mTRANSACTION (0.7ms)[0m  [1m[31mROLLBACK[0m
D, [2024-08-22T08:28:28.171102 #42] DEBUG -- :   [1m[35m (0.6ms)[0m  [1m[34mSELECT pg_advisory_unlock(1212213197400985920)[0m
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

Validation failed: User must exist
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:84:in `raise_validation_error'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:55:in `save!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:313:in `block in save!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:313:in `save!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/suppressor.rb:56:in `save!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:906:in `block in update!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:904:in `update!'
/var/app/db/data/20240815174852_add_owntracks_points_data.rb:44:in `update_point'
/var/app/db/data/20240815174852_add_owntracks_points_data.rb:29:in `block in up'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/relation/delegation.rb:100:in `each'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/relation/delegation.rb:100:in `each'
/var/app/db/data/20240815174852_add_owntracks_points_data.rb:26:in `up'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:989:in `public_send'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:989:in `exec_migration'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:969:in `block in migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:968:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1178:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1580:in `ddl_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1503:in `each'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1448:in `block in migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1448:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/data_migrate-9.4.0/lib/data_migrate/migration_context.rb:15:in `up'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1249:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/data_migrate-9.4.0/lib/data_migrate/tasks/data_migrate_tasks.rb:26:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/data_migrate-9.4.0/tasks/databases.rake:181:in `block (2 levels) in <main>'
/var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'

Caused by:
ActiveRecord::RecordInvalid: Validation failed: User must exist (ActiveRecord::RecordInvalid)
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:84:in `raise_validation_error'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:55:in `save!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:313:in `block in save!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:313:in `save!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/suppressor.rb:56:in `save!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:906:in `block in update!'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:904:in `update!'
/var/app/db/data/20240815174852_add_owntracks_points_data.rb:44:in `update_point'
/var/app/db/data/20240815174852_add_owntracks_points_data.rb:29:in `block in up'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/relation/delegation.rb:100:in `each'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/relation/delegation.rb:100:in `each'
/var/app/db/data/20240815174852_add_owntracks_points_data.rb:26:in `up'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:989:in `public_send'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:989:in `exec_migration'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:969:in `block in migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:968:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1178:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1580:in `ddl_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1503:in `each'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1448:in `block in migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1448:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/data_migrate-9.4.0/lib/data_migrate/migration_context.rb:15:in `up'
/var/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/migration.rb:1249:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/data_migrate-9.4.0/lib/data_migrate/tasks/data_migrate_tasks.rb:26:in `migrate'
/var/app/vendor/bundle/ruby/3.2.0/gems/data_migrate-9.4.0/tasks/databases.rake:181:in `block (2 levels) in <main>'
/var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => data:migrate
(See full trace by running task with --trace)
```

**Additional context**
I'm the only user of my Dawarich instance (user ID 1).

**Comment by rheicide** [comment]
@Freika There were indeed points without `user_id` in my database, and while I got `TypeError: can't cast User` with `Point.update_all(user: User.first)`, changing it to `Point.update_all(user_id: 1)` worked. I was able to upgrade my instance to 0.11.1 afterward.

Thanks a lot for your help, and for this useful piece of software!

**Comment by rantanlan** [comment]
had the same issue, around 6000 points missing. Was able to fix it with the above comments . Thanks a lot!
