### ISSUE TITLE
Dawarich broken

### ISSUE THREAD

**Issue by sunstep** [Freika/dawarich#232]
**Describe the bug**
Dawarich gives a 502 bad gateway when I visit the page after updating to 0.13.4

**Version**
0.13.4

**To Reproduce**
1. Update to 0.13.4

**Expected behavior**
Should start up properly

**Screenshots**

**Logs**

# Dawarich APP
Environment: development
dawarich_db (172.18.0.3:5432) open
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `require_relative': cannot load such file -- /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/unknown_command_spell_checker (LoadError)
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `require_relative'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
Environment: development
dawarich_db (172.18.0.3:5432) open
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `require_relative': cannot load such file -- /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/unknown_command_spell_checker (LoadError)
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `require_relative'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
Environment: development
dawarich_db (172.18.0.3:5432) open
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `require_relative': cannot load such file -- /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/unknown_command_spell_checker (LoadError)
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `require_relative'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
Environment: development
dawarich_db (172.18.0.3:5432) open
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `require_relative': cannot load such file -- /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/unknown_command_spell_checker (LoadError)
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `require_relative'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
Environment: development
dawarich_db (172.18.0.3:5432) open
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `require_relative': cannot load such file -- /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/unknown_command_spell_checker (LoadError)
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `require_relative'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
Environment: development
dawarich_db (172.18.0.3:5432) open
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `require_relative': cannot load such file -- /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/unknown_command_spell_checker (LoadError)
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/exceptions.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `require_relative'
	from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:1325:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'

# Dawarich Sidekiq

ERROR:  While executing gem ... (Gem::Package::FormatError)
    No such file or directory @ rb_sysopen - bundler-2.5.7.gem
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/package.rb:634:in `rescue in verify'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/package.rb:612:in `verify'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/package.rb:597:in `spec'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/installer.rb:291:in `spec'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/installer.rb:725:in `verify_spec'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/installer.rb:915:in `pre_install_checks'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/installer.rb:306:in `install'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:412:in `block in install_default_bundler_gem'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:400:in `chdir'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:400:in `install_default_bundler_gem'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:175:in `execute'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/command.rb:326:in `invoke_with_build_args'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/command_manager.rb:254:in `invoke_command'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/command_manager.rb:151:in `run'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/gem_runner.rb:56:in `run'
	setup.rb:36:in `<main>'

**Comment by sunstep** [comment]
Fixed, seems like it refused to work without updating the docker compose to add the hardware usage limitations.
