### ISSUE TITLE
REC file import fails

### ISSUE THREAD

**Issue by SayantanRC** [Freika/dawarich#332]
**Describe the bug**
I was thrilled to see import support for owntracks.rec file, alas it does not work.

**Version**
0.15.4

**To Reproduce**
Get owntracks .REC file, try to import it.

**Expected behavior**
The file should be imported.

**Screenshots**

**Logs**
```
Import "2024-08.rec" failed: no implicit conversion of nil into String, stacktrace: /var/app/vendor/bundle/ruby/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `initialize' /var/app/vendor/bundle/ruby/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `new' /var/app/vendor/bundle/ruby/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse' /var/app/app/services/own_tracks/rec_parser.rb:12:in `block in call' /var/app/app/services/own_tracks/rec_parser.rb:11:in `map' /var/app/app/services/own_tracks/rec_parser.rb:11:in `call' /var/app/app/services/own_tracks/export_parser.rb:35:in `parse_data' /var/app/app/services/own_tracks/export_parser.rb:13:in `call' /var/app/app/services/imports/create.rb:12:in `call' /var/app/app/models/import.rb:17:in `process!' /var/app/app/jobs/import_job.rb:10:in `perform' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/execution.rb:68:in `block in _perform_job' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/i18n-1.14.6/lib/i18n.rb:353:in `with_locale' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/translation.rb:9:in `block (2 levels) in ' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:130:in `instance_exec' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/core_ext/time/zones.rb:65:in `use_zone' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/timezones.rb:9:in `block (2 levels) in ' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:130:in `instance_exec' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:141:in `run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/execution.rb:67:in `_perform_job' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/instrumentation.rb:32:in `_perform_job' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/execution.rb:51:in `perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/instrumentation.rb:26:in `block in perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.1.1/lib/active_record/railties/job_runtime.rb:13:in `block in instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/instrumentation.rb:40:in `block in instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/notifications.rb:210:in `block in instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/notifications.rb:210:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/instrumentation.rb:39:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.1.1/lib/active_record/railties/job_runtime.rb:11:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/instrumentation.rb:26:in `perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/logging.rb:32:in `block in perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/logging.rb:41:in `tag_logger' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/logging.rb:32:in `perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/execution.rb:29:in `block in execute' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/railtie.rb:79:in `block (4 levels) in ' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/reloader.rb:77:in `block in wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/execution_wrapper.rb:87:in `wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/reloader.rb:74:in `wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/railtie.rb:78:in `block (3 levels) in ' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:130:in `instance_exec' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/callbacks.rb:141:in `run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/execution.rb:27:in `execute' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.1.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:70:in `perform' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:220:in `execute_job' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:185:in `block (4 levels) in process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:180:in `traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/job/interrupt_handler.rb:9:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/metrics/tracking.rb:26:in `track' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/metrics/tracking.rb:134:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:173:in `invoke' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:184:in `block (3 levels) in process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:145:in `block (6 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/job_retry.rb:118:in `local' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:144:in `block (5 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/rails.rb:16:in `block in call' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/reloader.rb:77:in `block in wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/execution_wrapper.rb:91:in `wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.1/lib/active_support/reloader.rb:74:in `wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/rails.rb:15:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:139:in `block (4 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:281:in `stats' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:134:in `block (3 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/job_logger.rb:23:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:133:in `block (2 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/job_retry.rb:85:in `global' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:132:in `block in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/job_logger.rb:50:in `prepare' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:131:in `dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:183:in `block (2 levels) in process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:182:in `handle_interrupt' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:182:in `block in process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:181:in `handle_interrupt' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:181:in `process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:86:in `process_one' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:76:in `run' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/component.rb:10:in `watchdog' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/component.rb:19:in `block in safe_thread' 
```

**Additional context**
Here are some of the lines of the REC files:  
```
2024-08-20T00:53:09Z	*                 	{"_type":"location","_id":"793719c4","acc":16,"alt":766,"batt":59,"bs":1,"conn":"w","created_at":1724115206,"lat":21.97701314,"lon":77.73266255999999,"m":1,"t":"u","tid":"go","topic":"owntracks/user/sargo","tst":1724115189,"vac":24,"vel":0,"_http":true}
2024-08-20T00:54:55Z	*                 	{"_type":"location","_id":"4cc5d81e","acc":21,"alt":815,"batt":58,"bs":1,"conn":"w","created_at":1724115295,"lat":21.97672805,"lon":77.73282494999999,"m":1,"t":"u","tid":"go","topic":"owntracks/user/sargo","tst":1724115295,"vac":24,"vel":0,"_http":true}
2024-08-20T00:54:58Z	*                 	{"_type":"location","_id":"f9f8bff1","acc":10,"alt":823,"batt":58,"bs":1,"conn":"w","created_at":1724115301,"lat":21.97671777,"lon":77.73286172,"m":1,"t":"u","tid":"go","topic":"owntracks/user/sargo","tst":1724115298,"vac":12,"vel":0,"_http":true}
```

**Comment by Freika** [comment]
Feel free to send your file to my Discord DM

**Comment by SayantanRC** [comment]
@Freika aren't the sample lines enough? I would have to edit nearly 8 MB worth data to obfuscate my real location.

**Comment by Freika** [comment]
@SayantanRC might be enough, might be not. I'll try to debug with the provided 3 lines then :)

**Comment by SayantanRC** [comment]
@Freika thank you so much. Can confirm it absolutely works. I really wanted to donate something but at the moment I have no money to spare 😅 But soon.

**Comment by Freika** [comment]
No worries, I'm not doing this for money (yet :D)
