### ISSUE TITLE
Error: Cannot find module 'daisyui' on every start (Low Priority

### ISSUE THREAD

**Issue by chrisl8** [Freika/dawarich#355]
Every time I start dawarich I see this in the log:

```
dawarich          | 14:18:11 css.1  |
dawarich          | 14:18:11 css.1  | Rebuilding...
dawarich          | 14:18:11 css.1  | Error: Cannot find module 'daisyui'
dawarich          | 14:18:11 css.1  | Require stack:
dawarich          | 14:18:11 css.1  | - /var/app/config/tailwind.config.js
dawarich          | 14:18:11 css.1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
dawarich          | 14:18:11 css.1  |     at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
dawarich          | 14:18:11 css.1  |     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
dawarich          | 14:18:11 css.1  |     at Function.resolve (/snapshot/tailwindcss/standalone-cli/patch-require.js:34:38)
dawarich          | 14:18:11 css.1  |     at _resolve (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:251148)
dawarich          | 14:18:11 css.1  |     at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:253746)
dawarich          | 14:18:11 css.1  |     at /var/app/config/tailwind.config.js:17:5
dawarich          | 14:18:11 css.1  |     at evalModule (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:256443)
dawarich          | 14:18:11 css.1  |     at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:254371)
dawarich          | 14:18:11 css.1  |     at /snapshot/tailwindcss/lib/lib/load-config.js:56:30 {
dawarich          | 14:18:11 css.1  |   code: 'MODULE_NOT_FOUND',
dawarich          | 14:18:11 css.1  |   requireStack: [ '/var/app/config/tailwind.config.js' ]
dawarich          | 14:18:11 css.1  | }
```

This doesn't prevent it from working, but is there a reason for this? Would it be non-trivial to fix this?

**Comment by Freika** [comment]
I think this one was resolved when I removed css watcher from Procfile.dev, so I'm closing it, but feel free to reopen it if it happens again
