### ISSUE TITLE
[BUG] import fail

### ISSUE THREAD

**Issue by shaman007** [Freika/dawarich#387]
**Describe the bug**
Importing my Google Takeout on the
```
    "latitudeE7": 492024663,
    "longitudeE7": 166234415,
    "accuracy": 16,
    "activity": [{
      "activity": [{
        "type": "STILL",
        "confidence": 56
      }, {
        "type": "ON_FOOT",
        "confidence": 18
      }, {
        "type": "WALKING",
        "confidence": 18
      }, {
        "type": "IN_VEHICLE",
        "confidence": 12
      }, {
        "type": "IN_ROAD_VEHICLE",
        "confidence": 12
      }, {
        "type": "IN_FOUR_WHEELER_VEHICLE",
        "confidence": 12
      }, {
        "type": "IN_CAR",
        "confidence": 12
      }, {
        "type": "IN_RAIL_VEHICLE",
        "confidence": 11
      }, {
        "type": "UNKNOWN",
        "confidence": 2
      }, {
        "type": "ON_BICYCLE",   <<< THIS LINE
        "confidence": 1
      }],
      "timestamp": "2020-09-23T20:59:22.936Z"
    }],
    "source": "WIFI",
    "deviceTag": -1055000194,
    "timestamp": "2020-09-23T20:58:51.721Z"
  },
```

I see a fail:

```
# bundle exec rake import:big_file['tmp/imports/watched/Records.json','user@domain.com']
[dotenv] Loaded .env.development
D, [2024-11-11T12:10:17.413607 #202] DEBUG -- :   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "user@domain.com"], ["LIMIT", 1]]
D, [2024-11-11T12:10:17.414353 #202] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:9:in `initialize'
D, [2024-11-11T12:10:17.501436 #202] DEBUG -- :   TRANSACTION (0.8ms)  BEGIN
D, [2024-11-11T12:10:17.502578 #202] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-11-11T12:10:17.503831 #202] DEBUG -- :   Import Create (3.2ms)  INSERT INTO "imports" ("name", "user_id", "source", "created_at", "updated_at", "raw_points", "doubles", "processed", "raw_data", "points_count") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["name", "tmp/imp
orts/watched/Records.json"], ["user_id", 1], ["source", 2], ["created_at", "2024-11-11 12:10:17.498905"], ["updated_at", "2024-11-11 12:10:17.498905"], ["raw_points", 0], ["doubles", 0], ["processed", 0], ["raw_data", nil], ["points_count", 0]]
D, [2024-11-11T12:10:17.504845 #202] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-11-11T12:10:17.509750 #202] DEBUG -- :   TRANSACTION (4.3ms)  COMMIT
D, [2024-11-11T12:10:17.510316 #202] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-11-11T12:10:17.510705 #202] DEBUG -- : Importing tmp/imports/watched/Records.json for user@domain.com, file size is 463409152... This might take a while, have patience!
rake aborted!
Oj::ParseError: quoted string not terminated (after locations[930086].activity[0].activity[9].type) at line 19565378, column 26 [parse.c:367] (Oj::ParseError)
/var/app/app/services/tasks/imports/google_records.rb:18:in `load'
/var/app/app/services/tasks/imports/google_records.rb:18:in `call'
/var/app/lib/tasks/import.rake:9:in `block (2 levels) in <main>'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => import:big_file
(See full trace by running task with --trace)
/var/app #
```

**Version**
0.16.3

**To Reproduce**
Create import task wity rake

**Comment by shaman007** [comment]
Now when I dropped this part, entire container fails with code 137
LOG:
```
Environment: development
postgres-postgresql.db.svc.cluster.local (10.43.219.108:5432) open
Successfully installed rubygems-update-3.5.7
Installing RubyGems 3.5.7
Successfully built RubyGem
Name: bundler
Version: 2.5.7
File: bundler-2.5.7.gem
Bundler 2.5.7 installed
RubyGems 3.5.7 installed
Regenerating binstubs
Regenerating plugins



------------------------------------------------------------------------------

RubyGems installed the following executables:
/usr/local/bin/gem
/usr/local/bin/bundle
/usr/local/bin/bundler

RubyGems system software updated
Successfully installed bundler-2.5.9
1 gem installed
Database dawarich_development already exists, skipping creation...
PostgreSQL is ready. Running database migrations...
[dotenv] Loaded .env.development
D, [2024-11-11T12:47:17.092521 #36] DEBUG -- : ActiveRecord::SchemaMigration Load (1.4ms) SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2024-11-11T12:47:17.169128 #36] DEBUG -- : ActiveRecord::SchemaMigration Load (0.8ms) SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Running DATA migrations...
[dotenv] Loaded .env.development
D, [2024-11-11T12:47:20.633979 #59] DEBUG -- : (0.4ms) SELECT pg_try_advisory_lock(1212213197400985920)
D, [2024-11-11T12:47:20.637770 #59] DEBUG -- : DataMigrate::DataSchemaMigration Load (2.2ms) SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
D, [2024-11-11T12:47:20.648136 #59] DEBUG -- : ActiveRecord::InternalMetadata Load (2.4ms) SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1 [[nil, "environment"]]
D, [2024-11-11T12:47:20.650107 #59] DEBUG -- : (0.7ms) SELECT pg_advisory_unlock(1212213197400985920)
D, [2024-11-11T12:47:20.655264 #59] DEBUG -- : DataMigrate::DataSchemaMigration Load (3.5ms) SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
Running seeds...
[dotenv] Loaded .env.development
D, [2024-11-11T12:47:24.190398 #72] DEBUG -- : ActiveRecord::SchemaMigration Load (2.8ms) SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2024-11-11T12:47:24.225190 #72] DEBUG -- : User Exists? (0.6ms) SELECT 1 AS one FROM "users" LIMIT $1 [["LIMIT", 1]]
=> Booting Puma
=> Rails 7.2.2 application starting in development
=> Run `bin/rails server --help` for more startup options
[dotenv] Loaded .env.development
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.4-p94) ("The Eagle of Durango")
* Min threads: 5
* Max threads: 10
* Environment: development
* PID: 85
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
D, [2024-11-11T12:48:08.097922 #85] DEBUG -- : ActiveRecord::SchemaMigration Load (1.8ms) SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2024-11-11T12:48:08.181762 #85] DEBUG -- : Rendering layout layouts/application.html.erb
D, [2024-11-11T12:48:08.181895 #85] DEBUG -- : Rendering home/index.html.erb within layouts/application
I, [2024-11-11T12:48:10.134519 #85] INFO -- : {"method":"GET","path":"/","format":"html","controller":"HomeController","action":"index","status":200,"allocations":310001,"duration":1990.27,"view":1959.81,"db":0.0}
F, [2024-11-11T12:48:11.460408 #85] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/images/bg-image.jpg"):

I, [2024-11-11T12:48:11.498530 #85] INFO -- : {"method":null,"path":null,"format":null,"params":{},"controller":"ApplicationCable::Connection","action":"connect","status":200,"allocations":2733,"duration":8.86}
I, [2024-11-11T12:48:11.501712 #85] INFO -- : {"method":null,"path":null,"format":null,"params":{},"controller":"ApplicationCable::Connection","action":"disconnect","status":200,"allocations":20,"duration":0.2}
D, [2024-11-11T12:48:11.542619 #85] DEBUG -- : Rendering layout vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/layout.erb
D, [2024-11-11T12:48:11.543429 #85] DEBUG -- : Rendering vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
D, [2024-11-11T12:48:11.720574 #85] DEBUG -- : Rendering vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
D, [2024-11-11T12:48:11.821111 #85] DEBUG -- : Rendering layout layouts/application.html.erb
D, [2024-11-11T12:48:11.821234 #85] DEBUG -- : Rendering devise/sessions/new.html.erb within layouts/application
I, [2024-11-11T12:48:11.859660 #85] INFO -- : {"method":"GET","path":"/users/sign_in","format":"html","controller":"Devise::SessionsController","action":"new","status":200,"allocations":33157,"duration":171.44,"view":40.47,"db":16.13}
D, [2024-11-11T12:48:13.314987 #85] DEBUG -- : User Load (1.4ms) SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2 [["email", "user@domain.com"], ["LIMIT", 1]]
D, [2024-11-11T12:48:13.316055 #85] DEBUG -- : ↳ app/controllers/application_controller.rb:11:in `unread_notifications'
```

**Comment by Freika** [comment]
@shaman007 have a look at https://github.com/Freika/dawarich/issues/142, the instruction on how to split your file (in case it's big) might be useful. If that's not your case, feel free to DM me your file in Discord and I'll debug it

**Comment by shaman007** [comment]
Closing, since no changes needed now
