### ISSUE TITLE
Google Phone Takeout fails to import

### ISSUE THREAD

**Issue by Jaconah** [Freika/dawarich#400]
**Describe the bug**
After exporting my Google Timeline Data from my phone (already migrated sadly), trying to import the data fails. 

**Version**
Include version of Dawarich you're experiencing problem on.

**To Reproduce**
1. Export data from phone
2. Configured a import from the web UI to import the data. 

**Expected behavior**
Data should be able to import as expected 

**Logs**
Import "location-history.json" failed: Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379/1), stacktrace: /usr/local/lib/ruby/3.3.0/socket.rb:1219:in `__connect_nonblock' /usr/local/lib/ruby/3.3.0/socket.rb:1219:in `connect_nonblock' /usr/local/lib/ruby/3.3.0/socket.rb:60:in `connect_internal' /usr/local/lib/ruby/3.3.0/socket.rb:141:in `connect' /usr/local/lib/ruby/3.3.0/socket.rb:647:in `block in tcp' /usr/local/lib/ruby/3.3.0/socket.rb:231:in `each' /usr/local/lib/ruby/3.3.0/socket.rb:231:in `foreach' /usr/local/lib/ruby/3.3.0/socket.rb:637:in `tcp' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client/ruby_connection.rb:119:in `connect' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client/ruby_connection.rb:51:in `initialize' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client.rb:746:in `new' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client.rb:746:in `block in connect' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client/middlewares.rb:12:in `connect' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client.rb:745:in `connect' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client.rb:732:in `raw_connection' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client.rb:697:in `ensure_connected' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-client-0.22.2/lib/redis_client.rb:292:in `call_v' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-5.3.0/lib/redis/client.rb:90:in `call_v' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-5.3.0/lib/redis.rb:152:in `block in send_command' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-5.3.0/lib/redis.rb:151:in `synchronize' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-5.3.0/lib/redis.rb:151:in `send_command' /var/app/vendor/bundle/ruby/3.3.0/gems/redis-5.3.0/lib/redis/commands/pubsub.rb:8:in `publish' /var/app/vendor/bundle/ruby/3.3.0/gems/actioncable-7.2.2/lib/action_cable/subscription_adapter/redis.rb:29:in `broadcast' /var/app/vendor/bundle/ruby/3.3.0/gems/actioncable-7.2.2/lib/action_cable/subscription_adapter/channel_prefix.rb:10:in `broadcast' /var/app/vendor/bundle/ruby/3.3.0/gems/actioncable-7.2.2/lib/action_cable/server/broadcasting.rb:56:in `block in broadcast' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/notifications.rb:210:in `block in instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/notifications.rb:210:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/actioncable-7.2.2/lib/action_cable/server/broadcasting.rb:54:in `broadcast' /var/app/vendor/bundle/ruby/3.3.0/gems/actioncable-7.2.2/lib/action_cable/server/broadcasting.rb:32:in `broadcast' /var/app/vendor/bundle/ruby/3.3.0/gems/actioncable-7.2.2/lib/action_cable/channel/broadcasting.rb:15:in `broadcast_to' /var/app/app/models/point.rb:45:in `broadcast_coordinates' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:362:in `block in make_lambda' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:208:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:563:in `block in invoke_after' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:563:in `each' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:563:in `invoke_after' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:111:in `run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:913:in `_run_commit_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/transactions.rb:385:in `committed!' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:307:in `block in commit_records' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:344:in `run_action_on_records' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:306:in `commit_records' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:596:in `block in commit_transaction' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:584:in `commit_transaction' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:628:in `block in within_new_transaction' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:613:in `within_new_transaction' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:361:in `transaction' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/transactions.rb:414:in `block in with_transaction_returning_status' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `with_connection' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_handling.rb:296:in `with_connection' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/transactions.rb:410:in `with_transaction_returning_status' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/transactions.rb:362:in `save' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/suppressor.rb:52:in `save' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/persistence.rb:38:in `create' /var/app/app/services/google_maps/phone_takeout_parser.rb:24:in `block in call' /var/app/app/services/google_maps/phone_takeout_parser.rb:16:in `each' /var/app/app/services/google_maps/phone_takeout_parser.rb:16:in `with_index' /var/app/app/services/google_maps/phone_takeout_parser.rb:16:in `call' /var/app/app/services/imports/create.rb:12:in `call' /var/app/app/models/import.rb:17:in `process!' /var/app/app/jobs/import_job.rb:10:in `perform' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/execution.rb:68:in `block in _perform_job' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/i18n-1.14.6/lib/i18n.rb:353:in `with_locale' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/translation.rb:9:in `block (2 levels) in ' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:130:in `instance_exec' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:130:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/core_ext/time/zones.rb:65:in `use_zone' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/timezones.rb:9:in `block (2 levels) in ' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:130:in `instance_exec' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:130:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:141:in `run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/execution.rb:67:in `_perform_job' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/instrumentation.rb:32:in `_perform_job' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/execution.rb:51:in `perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/instrumentation.rb:26:in `block in perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/railties/job_runtime.rb:13:in `block in instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/instrumentation.rb:40:in `block in instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/notifications.rb:210:in `block in instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/notifications.rb:210:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/instrumentation.rb:39:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/railties/job_runtime.rb:11:in `instrument' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/instrumentation.rb:26:in `perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/logging.rb:32:in `block in perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/logging.rb:41:in `tag_logger' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/logging.rb:32:in `perform_now' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/execution.rb:29:in `block in execute' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/railtie.rb:79:in `block (4 levels) in ' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/reloader.rb:77:in `block in wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/reloader.rb:74:in `wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/railtie.rb:78:in `block (3 levels) in ' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:130:in `instance_exec' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:130:in `block in run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:141:in `run_callbacks' /var/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2/lib/active_job/execution.rb:27:in `execute' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:10:in `perform' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:220:in `execute_job' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:185:in `block (4 levels) in process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/middleware/chain.rb:180:in `traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/job/interrupt_handler.rb:9:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/middleware/chain.rb:182:in `traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/metrics/tracking.rb:26:in `track' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/metrics/tracking.rb:134:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/middleware/chain.rb:182:in `traverse' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/middleware/chain.rb:173:in `invoke' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:184:in `block (3 levels) in process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:145:in `block (6 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/job_retry.rb:118:in `local' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:144:in `block (5 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/rails.rb:22:in `block in call' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/reloader.rb:77:in `block in wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/execution_wrapper.rb:91:in `wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/reloader.rb:74:in `wrap' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/rails.rb:21:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:139:in `block (4 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:281:in `stats' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:134:in `block (3 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/job_logger.rb:23:in `call' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:133:in `block (2 levels) in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/job_retry.rb:85:in `global' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:132:in `block in dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/job_logger.rb:50:in `prepare' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:131:in `dispatch' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:183:in `block (2 levels) in process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:182:in `handle_interrupt' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:182:in `block in process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:181:in `handle_interrupt' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:181:in `process' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:86:in `process_one' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/processor.rb:76:in `run' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/component.rb:10:in `watchdog' /var/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.4/lib/sidekiq/component.rb:19:in `block in safe_thread'
Please, when reporting a bug to [Github Issues](https://github.com/Freika/dawarich/issues), don't forget to include logs from dawarich_app and dawarich_sidekiq docker containers. Thank you!

I don't see any screaming errors in dawarich_app, however after I see the long block of my import in the sidekiq container theses are the logs after it (before it includes personal location data again)
2024-11-13T15:48:35.673Z pid=111 tid=9z83 WARN: Redis::CannotConnectError: Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379/1)

2024-11-13T15:48:35.674Z pid=111 tid=9z83 WARN: app/models/point.rb:45:in `broadcast_coordinates'

app/jobs/overland/batch_creating_job.rb:12:in `block in perform'

app/jobs/overland/batch_creating_job.rb:9:in `each'

app/jobs/overland/batch_creating_job.rb:9:in `perform'

2024-11-13T15:48:55.759Z pid=111 tid=9zdj class=ReverseGeocodingJob jid=0e4e0dd69c12b5e3d2881d75 INFO: start

I, [2024-11-13T15:48:55.771634 #111]  INFO -- : Performing ReverseGeocodingJob (Job ID: 060cee9e-452d-4d35-94e3-630f43599c0f) from Sidekiq(reverse_geocoding) enqueued at 2024-11-13T15:48:35.631981341Z with arguments: "Point", 1878

D, [2024-11-13T15:48:55.773139 #111] DEBUG -- :   Point Load (0.4ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 1878], ["LIMIT", 1]]

D, [2024-11-13T15:48:55.773603 #111] DEBUG -- :   ↳ app/services/reverse_geocoding/points/fetch_data.rb:7:in `initialize'

D, [2024-11-13T15:48:56.382261 #111] DEBUG -- :   TRANSACTION (0.5ms)  BEGIN

D, [2024-11-13T15:48:56.385448 #111] DEBUG -- :   ↳ app/services/reverse_geocoding/points/fetch_data.rb:18:in `call'

D, [2024-11-13T15:48:56.386670 #111] DEBUG -- :   User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]

D, [2024-11-13T15:48:56.389592 #111] DEBUG -- :   ↳ app/services/reverse_geocoding/points/fetch_data.rb:18:in `call'

**Additional context**

**Comment by shaman007** [comment]
```
Connection refused - connect(2) for 127.0.0.1:6379  redis://localhost:6379/1
```

That mean the Redis is not up or unavalible.

**Comment by Freika** [comment]
@Jaconah I think it's related to a problem fixed in 0.16.4, can you try to update and repeat importing attempt?

**Comment by ptrsmk** [comment]
I'm on the latest version, fresh install today, and have an import file of about 140MB that is seemingly just sitting there with no activity. No errors in the logs. No failures in Sidekiq.

**Comment by Freika** [comment]
@ptrsmk is your sidekiq in the same docker network as the app?

**Comment by ptrsmk** [comment]
Yes, it is.

**Comment by Freika** [comment]
@ptrsmk is your issue still persists? The problem with connection to redis was solved, but maybe you're experiencing some other errors?

**Comment by ptrsmk** [comment]
I haven't retested. I managed to import it by splitting the file into smaller chunks.

**Comment by Freika** [comment]
Closing this then, glad you managed to import your data!
