### ISSUE TITLE
ERR_CONNECTION_REFUSED after latest update (ERROR:  While executing gem ... (Errno::ENOENT))

### ISSUE THREAD

**Issue by Coysh** [Freika/dawarich#458]
**Describe the bug**
Unable to connect

**Version**
Latest

**Expected behavior**
Open Dawarich

**Logs**
```
dawarich-dawarich_redis-1  | 9424:C 30 Nov 2024 09:43:37.071 * DB saved on disk
dawarich-dawarich_redis-1  | 9424:C 30 Nov 2024 09:43:37.071 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:43:37.168 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:48:38.019 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:48:38.020 * Background saving started by pid 9425
dawarich-dawarich_redis-1  | 9425:C 30 Nov 2024 09:48:38.023 * DB saved on disk
dawarich-dawarich_redis-1  | 9425:C 30 Nov 2024 09:48:38.023 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:48:38.120 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:53:39.081 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:53:39.081 * Background saving started by pid 9426
dawarich-dawarich_redis-1  | 9426:C 30 Nov 2024 09:53:39.085 * DB saved on disk
dawarich-dawarich_redis-1  | 9426:C 30 Nov 2024 09:53:39.085 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:53:39.181 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:58:40.020 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:58:40.020 * Background saving started by pid 9427
dawarich-dawarich_redis-1  | 9427:C 30 Nov 2024 09:58:40.024 * DB saved on disk
dawarich-dawarich_redis-1  | 9427:C 30 Nov 2024 09:58:40.024 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 09:58:40.121 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:03:41.082 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:03:41.082 * Background saving started by pid 9428
dawarich-dawarich_redis-1  | 9428:C 30 Nov 2024 10:03:41.085 * DB saved on disk
dawarich-dawarich_redis-1  | 9428:C 30 Nov 2024 10:03:41.086 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:03:41.183 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:08:42.023 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:08:42.023 * Background saving started by pid 9429
dawarich-dawarich_redis-1  | 9429:C 30 Nov 2024 10:08:42.027 * DB saved on disk
dawarich-dawarich_redis-1  | 9429:C 30 Nov 2024 10:08:42.027 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:08:42.124 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:13:43.048 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:13:43.049 * Background saving started by pid 9430
dawarich-dawarich_redis-1  | 9430:C 30 Nov 2024 10:13:43.052 * DB saved on disk
dawarich-dawarich_redis-1  | 9430:C 30 Nov 2024 10:13:43.052 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:13:43.149 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:18:44.061 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:18:44.061 * Background saving started by pid 9431
dawarich-dawarich_redis-1  | 9431:C 30 Nov 2024 10:18:44.065 * DB saved on disk
dawarich-dawarich_redis-1  | 9431:C 30 Nov 2024 10:18:44.065 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:18:44.162 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:23:45.099 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:23:45.100 * Background saving started by pid 9432
dawarich-dawarich_redis-1  | 9432:C 30 Nov 2024 10:23:45.103 * DB saved on disk
dawarich-dawarich_redis-1  | 9432:C 30 Nov 2024 10:23:45.103 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:23:45.200 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:28:46.071 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:28:46.071 * Background saving started by pid 9433
dawarich-dawarich_redis-1  | 9433:C 30 Nov 2024 10:28:46.075 * DB saved on disk
dawarich-dawarich_redis-1  | 9433:C 30 Nov 2024 10:28:46.075 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:28:46.173 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:33:47.003 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:33:47.003 * Background saving started by pid 9434
dawarich-dawarich_redis-1  | 9434:C 30 Nov 2024 10:33:47.006 * DB saved on disk
dawarich-dawarich_redis-1  | 9434:C 30 Nov 2024 10:33:47.007 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:33:47.104 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:38:48.047 * 100 changes in 300 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:38:48.047 * Background saving started by pid 9435
dawarich-dawarich_redis-1  | 9435:C 30 Nov 2024 10:38:48.050 * DB saved on disk
dawarich-dawarich_redis-1  | 9435:C 30 Nov 2024 10:38:48.051 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:38:48.148 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:signal-handler (1732963225) Received SIGTERM scheduling shutdown...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:25.278 # User requested shutdown...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:25.278 * Saving the final RDB snapshot before exiting.
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:25.281 * DB saved on disk
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:25.281 # Redis is now ready to exit, bye bye...
dawarich-dawarich_redis-1  | 1:C 30 Nov 2024 10:40:55.589 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
dawarich-dawarich_redis-1  | 1:C 30 Nov 2024 10:40:55.589 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
dawarich-dawarich_redis-1  | 1:C 30 Nov 2024 10:40:55.589 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.590 * monotonic clock: POSIX clock_gettime
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.591 * Running mode=standalone, port=6379.
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.591 # Server initialized
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.591 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.591 * Loading RDB produced by version 7.0.15
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.591 * RDB age 30 seconds
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.591 * RDB memory usage when created 1.93 Mb
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.592 * Done loading RDB, keys loaded: 172, keys expired: 1.
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.592 * DB loaded from disk: 0.000 seconds
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:40:55.592 * Ready to accept connections
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:44:27.853 * 10000 changes in 60 seconds. Saving...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:44:27.854 * Background saving started by pid 20
dawarich-dawarich_redis-1  | 20:C 30 Nov 2024 10:44:27.857 * DB saved on disk
dawarich-dawarich_redis-1  | 20:C 30 Nov 2024 10:44:27.858 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:44:27.954 * Background saving terminated with success
dawarich-dawarich_redis-1  | 1:signal-handler (1732963483) Received SIGTERM scheduling shutdown...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:44:43.101 # User requested shutdown...
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:44:43.101 * Saving the final RDB snapshot before exiting.
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:44:43.103 * DB saved on disk
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:44:43.103 # Redis is now ready to exit, bye bye...
dawarich-dawarich_redis-1  | 1:C 30 Nov 2024 10:45:02.004 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
dawarich-dawarich_redis-1  | 1:C 30 Nov 2024 10:45:02.004 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
dawarich-dawarich_redis-1  | 1:C 30 Nov 2024 10:45:02.004 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.005 * monotonic clock: POSIX clock_gettime
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.005 * Running mode=standalone, port=6379.
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.005 # Server initialized
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.005 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.006 * Loading RDB produced by version 7.0.15
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.006 * RDB age 19 seconds
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.006 * RDB memory usage when created 1.62 Mb
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.006 * Done loading RDB, keys loaded: 172, keys expired: 1.
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.006 * DB loaded from disk: 0.000 seconds
dawarich-dawarich_redis-1  | 1:M 30 Nov 2024 10:45:02.006 * Ready to accept connections
dawarich_app               | Latest version already installed. Done.
dawarich_sidekiq           | Latest version already installed. Done.
dawarich_app               | ERROR:  While executing gem ... (Errno::ENOENT)
dawarich_app               |     No such file or directory @ apply2files - /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/parser/arguments.rb
dawarich_app               |    /usr/local/lib/ruby/3.3.0/fileutils.rb:2210:in `chmod'
dawarich_app               |    /usr/local/lib/ruby/3.3.0/fileutils.rb:2210:in `chmod'
dawarich_app               |    /usr/local/lib/ruby/3.3.0/fileutils.rb:1808:in `block in chmod'
dawarich_app               |    /usr/local/lib/ruby/3.3.0/fileutils.rb:1807:in `each'
dawarich_app               |    /usr/local/lib/ruby/3.3.0/fileutils.rb:1807:in `chmod'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:457:in `block (2 levels) in extract_tar_gz'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package/tar_reader.rb:65:in `each'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:425:in `block in extract_tar_gz'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:548:in `block in open_tar_gz'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:545:in `wrap'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:545:in `open_tar_gz'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:424:in `extract_tar_gz'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:398:in `block (2 levels) in extract_files'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package/tar_reader.rb:65:in `each'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:395:in `block in extract_files'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package/file_source.rb:30:in `open'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package/file_source.rb:30:in `with_read_io'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:392:in `extract_files'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/installer.rb:861:in `extract_files'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/installer.rb:328:in `install'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/resolver/specification.rb:105:in `install'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/request_set.rb:195:in `block in install'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/request_set.rb:183:in `each'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/request_set.rb:183:in `install'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/commands/install_command.rb:207:in `install_gem'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/commands/install_command.rb:216:in `each'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/commands/install_command.rb:216:in `install_gems'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/commands/install_command.rb:162:in `execute'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:254:in `invoke_command'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:193:in `process_args'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:151:in `run'
dawarich_app               |    /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
dawarich_app               |    /usr/local/bin/gem:12:in `<main>'
dawarich_sidekiq           | Successfully installed bundler-2.5.9
dawarich_sidekiq           | 1 gem installed
dawarich_sidekiq           | Database dawarich_development already exists, skipping creation...
dawarich_sidekiq           | PostgreSQL is ready. Running database migrations...
dawarich_app exited with code 0
dawarich_app               | Latest version already installed. Done.
dawarich_app               | Successfully installed bundler-2.5.9
dawarich_app               | 1 gem installed
dawarich_app               | Database dawarich_development already exists, skipping creation...
dawarich_app               | PostgreSQL is ready. Running database migrations...
dawarich_sidekiq           | [dotenv] Set DATABASE_PORT and PHOTON_API_HOST
dawarich_sidekiq           | [dotenv] Loaded .env.development
dawarich_sidekiq           | 2024-11-30T10:45:08.472Z pid=24 tid=46s INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_sidekiq           | D, [2024-11-30T10:45:09.205639 #24] DEBUG -- :   ActiveRecord::SchemaMigration Load (2.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_sidekiq           | D, [2024-11-30T10:45:09.274786 #24] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_sidekiq           | Running DATA migrations...
dawarich_app               | [dotenv] Set DATABASE_PORT and PHOTON_API_HOST
dawarich_app               | [dotenv] Loaded .env.development
dawarich_app               | 2024-11-30T10:45:10.757Z pid=24 tid=46s INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_app               | D, [2024-11-30T10:45:11.507234 #24] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app               | D, [2024-11-30T10:45:11.544628 #24] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app               | Running DATA migrations...
dawarich_sidekiq           | [dotenv] Set DATABASE_PORT and PHOTON_API_HOST
dawarich_sidekiq           | [dotenv] Loaded .env.development
dawarich_sidekiq           | 2024-11-30T10:45:12.687Z pid=49 tid=49t INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_sidekiq           | D, [2024-11-30T10:45:13.312684 #49] DEBUG -- :    (0.3ms)  SELECT pg_try_advisory_lock(1212213197400985920)
dawarich_sidekiq           | D, [2024-11-30T10:45:13.355214 #49] DEBUG -- :   DataMigrate::DataSchemaMigration Load (2.8ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
dawarich_sidekiq           | D, [2024-11-30T10:45:13.359826 #49] DEBUG -- :   ActiveRecord::InternalMetadata Load (2.0ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
dawarich_sidekiq           | D, [2024-11-30T10:45:13.360888 #49] DEBUG -- :    (0.3ms)  SELECT pg_advisory_unlock(1212213197400985920)
dawarich_sidekiq           | D, [2024-11-30T10:45:13.361984 #49] DEBUG -- :   DataMigrate::DataSchemaMigration Load (0.3ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
dawarich_sidekiq           | Running seeds...
dawarich_app               | [dotenv] Set DATABASE_PORT and PHOTON_API_HOST
dawarich_app               | [dotenv] Loaded .env.development
dawarich_app               | 2024-11-30T10:45:14.947Z pid=49 tid=49t INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_app               | D, [2024-11-30T10:45:15.587207 #49] DEBUG -- :    (0.3ms)  SELECT pg_try_advisory_lock(1212213197400985920)
dawarich_app               | D, [2024-11-30T10:45:15.589619 #49] DEBUG -- :   DataMigrate::DataSchemaMigration Load (1.5ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
dawarich_app               | D, [2024-11-30T10:45:15.632787 #49] DEBUG -- :   ActiveRecord::InternalMetadata Load (1.6ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
dawarich_app               | D, [2024-11-30T10:45:15.633841 #49] DEBUG -- :    (0.3ms)  SELECT pg_advisory_unlock(1212213197400985920)
dawarich_app               | D, [2024-11-30T10:45:15.635708 #49] DEBUG -- :   DataMigrate::DataSchemaMigration Load (0.3ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
dawarich_app               | Running seeds...
dawarich_sidekiq           | [dotenv] Set DATABASE_PORT and PHOTON_API_HOST
dawarich_sidekiq           | [dotenv] Loaded .env.development
dawarich_sidekiq           | 2024-11-30T10:45:16.766Z pid=64 tid=4b4 INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_sidekiq           | D, [2024-11-30T10:45:17.401819 #64] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_sidekiq           | D, [2024-11-30T10:45:17.466527 #64] DEBUG -- :   User Exists? (1.5ms)  SELECT 1 AS one FROM "users" LIMIT $1  [["LIMIT", 1]]
dawarich_app               | [dotenv] Set DATABASE_PORT and PHOTON_API_HOST
dawarich_app               | [dotenv] Loaded .env.development
dawarich_app               | 2024-11-30T10:45:19.033Z pid=64 tid=4b4 INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_app               | D, [2024-11-30T10:45:19.667185 #64] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app               | D, [2024-11-30T10:45:19.688244 #64] DEBUG -- :   User Exists? (1.0ms)  SELECT 1 AS one FROM "users" LIMIT $1  [["LIMIT", 1]]
dawarich_app               | Starting Foreman with Procfile.dev...
dawarich_app               | 10:45:21 web.1  | started with pid 84
dawarich_sidekiq           | [dotenv] Set DATABASE_PORT and PHOTON_API_HOST
dawarich_sidekiq           | [dotenv] Loaded .env.development
dawarich_sidekiq           | 2024-11-30T10:45:22.478Z pid=79 tid=3vn INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_sidekiq           | 
dawarich_sidekiq           | 
dawarich_sidekiq           |                m,
dawarich_sidekiq           |                `$b
dawarich_sidekiq           |           .ss,  $$:         .,d$
dawarich_sidekiq           |           `$$P,d$P'    .,md$P"'
dawarich_sidekiq           |            ,$$$$$b/md$$$P^'
dawarich_sidekiq           |          .d$$$$$$/$$$P'
dawarich_sidekiq           |          $$^' `"/$$$'       ____  _     _      _    _
dawarich_sidekiq           |          $:    ',$$:       / ___|(_) __| | ___| | _(_) __ _
dawarich_sidekiq           |          `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
dawarich_sidekiq           |                 $$:         ___) | | (_| |  __/   <| | (_| |
dawarich_sidekiq           |                 $$         |____/|_|\__,_|\___|_|\_\_|\__, |
dawarich_sidekiq           |               .d$$                                       |_|
dawarich_sidekiq           |       
dawarich_sidekiq           | 
dawarich_sidekiq           | 2024-11-30T10:45:23.164Z pid=79 tid=3vn INFO: Booted Rails 7.2.2 application in development environment
dawarich_sidekiq           | 2024-11-30T10:45:23.165Z pid=79 tid=3vn INFO: Running in ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux-musl]
dawarich_sidekiq           | 2024-11-30T10:45:23.165Z pid=79 tid=3vn INFO: See LICENSE and the LGPL-3.0 for licensing details.
dawarich_sidekiq           | 2024-11-30T10:45:23.165Z pid=79 tid=3vn INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
dawarich_sidekiq           | 2024-11-30T10:45:23.165Z pid=79 tid=3vn INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"default", :url=>"redis://dawarich_redis:6379/0"}
dawarich_sidekiq           | 2024-11-30T10:45:23.384Z pid=79 tid=3vn INFO: Starting processing, hit Ctrl-C to stop
dawarich_app               | 10:45:24 web.1  | => Booting Puma
dawarich_app               | 10:45:24 web.1  | => Rails 7.2.2 application starting in development 
dawarich_app               | 10:45:24 web.1  | => Run `bin/rails server --help` for more startup options
dawarich_app               | 10:45:24 web.1  | [dotenv] Set DATABASE_PORT and PHOTON_API_HOST
dawarich_app               | 10:45:24 web.1  | [dotenv] Loaded .env.development
dawarich_app               | 10:45:24 web.1  | 2024-11-30T10:45:24.235Z pid=84 tid=3ps INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_app               | 10:45:24 web.1  | [84] Puma starting in cluster mode...
dawarich_app               | 10:45:24 web.1  | [84] * Puma version: 6.5.0 ("Sky's Version")
dawarich_app               | 10:45:24 web.1  | [84] * Ruby version: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux-musl]
dawarich_app               | 10:45:24 web.1  | [84] *  Min threads: 5
dawarich_app               | 10:45:24 web.1  | [84] *  Max threads: 5
dawarich_app               | 10:45:24 web.1  | [84] *  Environment: development
dawarich_app               | 10:45:24 web.1  | [84] *   Master PID: 84
dawarich_app               | 10:45:24 web.1  | [84] *      Workers: 2
dawarich_app               | 10:45:24 web.1  | [84] *     Restarts: (✔) hot (✖) phased
dawarich_app               | 10:45:24 web.1  | [84] * Preloading application
dawarich_app               | 10:45:24 web.1  | [84] * Listening on http://0.0.0.0:3000
dawarich_app               | 10:45:24 web.1  | [84] Use Ctrl-C to stop
dawarich_app               | 10:45:24 web.1  | [84] - Worker 0 (PID: 98) booted in 0.0s, phase: 0
dawarich_app               | 10:45:24 web.1  | [84] - Worker 1 (PID: 105) booted in 0.0s, phase: 0
```

**Additional context**

**Comment by Freika** [comment]
@Coysh in your docker compose change volumes:

```yml
...
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - gem_cache_app:/usr/local/bundle/gems_app
...
dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - gem_cache_sidekiq:/usr/local/bundle/gems_sidekiq
...
volumes:
  db_data:
  gem_cache_app:
  gem_cache_sidekiq:
  shared_data:
  public:
  watched:
```
