### ISSUE TITLE
Error on /map page after upgrade to v0.19.4

### ISSUE THREAD

**Issue by whimsical-c4lic0** [Freika/dawarich#522]
**Describe the bug**
I just upgraded my docker containers (application and sidekiq) to `freikin/dawarich:0.19.4`. Looking at the logs, the database migrations ran successfully, and the application started normally. After logging in, I am redirected to an error page. The error is in the map controller, and other pages load normally by changing the url to `/points`, `/stats`, etc.

**Version**
0.19.4

**To Reproduce**
1. Upgrade docker containers to 0.19.4
2. Login with normal credentials
3. Follow the redirect after login, or navigate to `/map`

**Expected behavior**
Map page loads without error.

**Screenshots**
![Screenshot 2024-12-10 150125](https://github.com/user-attachments/assets/5076e0ab-8b1e-4389-944f-830799ae5830)

**Logs**
```
15:00:28 web.1  | I, [2024-12-10T15:00:28.757887 #105]  INFO -- : {"method":null,"path":null,"format":null,"params":null,"controller":"NotificationsChannel","action":"unsubscribe","status":200,"allocations":19,"duration":0.06}
15:00:28 web.1  | I, [2024-12-10T15:00:28.758168 #105]  INFO -- : {"method":null,"path":null,"format":null,"params":null,"controller":"PointsChannel","action":"unsubscribe","status":200,"allocations":32,"duration":0.13}
15:00:28 web.1  | I, [2024-12-10T15:00:28.758501 #105]  INFO -- : {"method":null,"path":null,"format":null,"params":null,"controller":"ImportsChannel","action":"unsubscribe","status":200,"allocations":32,"duration":0.1}
15:00:28 web.1  | I, [2024-12-10T15:00:28.758628 #105]  INFO -- : {"method":null,"path":null,"format":null,"params":{},"controller":"ApplicationCable::Connection","action":"disconnect","status":200,"allocations":223,"duration":0.91}
15:00:28 web.1  | D, [2024-12-10T15:00:28.792242 #115] DEBUG -- :   User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
15:00:28 web.1  | D, [2024-12-10T15:00:28.792739 #115] DEBUG -- :   ↳ app/controllers/application_controller.rb:11:in `unread_notifications'
15:00:28 web.1  | D, [2024-12-10T15:00:28.794640 #115] DEBUG -- :   Point Exists? (0.7ms)  SELECT 1 AS one FROM "points" WHERE "points"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
15:00:28 web.1  | D, [2024-12-10T15:00:28.795013 #115] DEBUG -- :   ↳ app/controllers/map_controller.rb:23:in `start_at'
15:00:28 web.1  | D, [2024-12-10T15:00:28.796501 #115] DEBUG -- :   Point Load (0.7ms)  SELECT "points"."id", "points"."battery_status", "points"."ping", "points"."battery", "points"."tracker_id", "points"."topic", "points"."altitude", "points"."longitude", "points"."velocity", "points"."trigger", "points"."bssid", "points"."ssid", "points"."connection", "points"."vertical_accuracy", "points"."accuracy", "points"."timestamp", "points"."latitude", "points"."mode", "points"."inrids", "points"."in_regions", "points"."import_id", "points"."city", "points"."country", "points"."created_at", "points"."updated_at", "points"."user_id", "points"."geodata", "points"."visit_id", "points"."reverse_geocoded_at" FROM "points" WHERE "points"."user_id" = $1 ORDER BY "points"."timestamp" DESC LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
15:00:28 web.1  | D, [2024-12-10T15:00:28.796964 #115] DEBUG -- :   ↳ app/controllers/map_controller.rb:23:in `start_at'
15:00:28 web.1  | D, [2024-12-10T15:00:28.797875 #115] DEBUG -- :   CACHE Point Exists? (0.0ms)  SELECT 1 AS one FROM "points" WHERE "points"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
15:00:28 web.1  | D, [2024-12-10T15:00:28.798151 #115] DEBUG -- :   ↳ app/controllers/map_controller.rb:30:in `end_at'
15:00:28 web.1  | D, [2024-12-10T15:00:28.798855 #115] DEBUG -- :   CACHE Point Load (0.0ms)  SELECT "points"."id", "points"."battery_status", "points"."ping", "points"."battery", "points"."tracker_id", "points"."topic", "points"."altitude", "points"."longitude", "points"."velocity", "points"."trigger", "points"."bssid", "points"."ssid", "points"."connection", "points"."vertical_accuracy", "points"."accuracy", "points"."timestamp", "points"."latitude", "points"."mode", "points"."inrids", "points"."in_regions", "points"."import_id", "points"."city", "points"."country", "points"."created_at", "points"."updated_at", "points"."user_id", "points"."geodata", "points"."visit_id", "points"."reverse_geocoded_at" FROM "points" WHERE "points"."user_id" = $1 ORDER BY "points"."timestamp" DESC LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
15:00:28 web.1  | D, [2024-12-10T15:00:28.799179 #115] DEBUG -- :   ↳ app/controllers/map_controller.rb:30:in `end_at'
15:00:28 web.1  | D, [2024-12-10T15:00:28.800801 #115] DEBUG -- :   Point Load (0.7ms)  SELECT "points"."id", "points"."battery_status", "points"."ping", "points"."battery", "points"."tracker_id", "points"."topic", "points"."altitude", "points"."longitude", "points"."velocity", "points"."trigger", "points"."bssid", "points"."ssid", "points"."connection", "points"."vertical_accuracy", "points"."accuracy", "points"."timestamp", "points"."latitude", "points"."mode", "points"."inrids", "points"."in_regions", "points"."import_id", "points"."city", "points"."country", "points"."created_at", "points"."updated_at", "points"."user_id", "points"."geodata", "points"."visit_id", "points"."reverse_geocoded_at" FROM "points" WHERE "points"."user_id" = $1 AND (timestamp >= $2 AND timestamp <= $3) ORDER BY "points"."timestamp" ASC  [["user_id", 1], [nil, 1733810400], [nil, 1733896799]]
15:00:28 web.1  | D, [2024-12-10T15:00:28.801289 #115] DEBUG -- :   ↳ app/services/countries_and_cities.rb:20:in `group_by'
15:00:28 web.1  | I, [2024-12-10T15:00:28.802773 #115]  INFO -- : {"method":"GET","path":"/map","format":"html","controller":"MapController","action":"index","status":500,"allocations":6466,"duration":12.4,"view":0.0,"db":2.4}
15:00:28 web.1  | F, [2024-12-10T15:00:28.803440 #115] FATAL -- :   
15:00:28 web.1  | NoMethodError (undefined method `to_coordinates' for an instance of Array):
15:00:28 web.1  |   
15:00:28 web.1  | app/services/distance_calculator.rb:11:in `call'
15:00:28 web.1  | app/controllers/map_controller.rb:39:in `block in distance'
15:00:28 web.1  | app/controllers/map_controller.rb:38:in `each'
15:00:28 web.1  | app/controllers/map_controller.rb:38:in `each_cons'
15:00:28 web.1  | app/controllers/map_controller.rb:38:in `distance'
15:00:28 web.1  | app/controllers/map_controller.rb:13:in `index'
15:00:29 web.1  | D, [2024-12-10T15:00:29.029774 #115] DEBUG -- :   Rendering layout vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/layout.erb
15:00:29 web.1  | D, [2024-12-10T15:00:29.029835 #115] DEBUG -- :   Rendering vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
15:00:29 web.1  | D, [2024-12-10T15:00:29.039048 #115] DEBUG -- :   Rendering vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
15:00:29 web.1  | F, [2024-12-10T15:00:29.120158 #115] FATAL -- :   
15:00:29 web.1  | ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
15:00:29 web.1  |   
15:00:29 web.1  | D, [2024-12-10T15:00:29.154025 #115] DEBUG -- :   Rendering layout vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/layout.erb
15:00:29 web.1  | D, [2024-12-10T15:00:29.154088 #115] DEBUG -- :   Rendering vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
15:00:29 web.1  | D, [2024-12-10T15:00:29.264182 #115] DEBUG -- :   Rendering vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
```

**Comment by whimsical-c4lic0** [comment]
I was able to replicate the error with a fresh install (empty database) by following these steps:
1. Clone the repo
2. Run `docker compose up` and wait for the application to start
3. Log in with default credentials
4. Add an immich url and api key to `/settings`
5. Navigate to `/imports`, and start an immich data import
6. Wait a few seconds for a few points to be imported
7. Navigate to the map page

**Comment by Freika** [comment]
Will be fixed in https://github.com/Freika/dawarich/releases/tag/0.19.5, you can update as soon as the docker image is built
