### ISSUE TITLE
Error while upgrading database to v0.19.4

### ISSUE THREAD

**Issue by elmuz** [Freika/dawarich#523]
**Describe the bug**
I am getting this in the postgre container.
```
2024-12-10 21:28:49.320 UTC [637] ERROR:  column "reverse_geocoded_at" of relation "points" already exists
2024-12-10 21:28:49.320 UTC [637] STATEMENT:  ALTER TABLE "points" ADD "reverse_geocoded_at" timestamp(6)
```

**Version**
v0.19.4

**To Reproduce**
In theory, simply updating the docker image and restart the database container

**Logs**
This is a bit more verbose
```
Caused by:
PG::DuplicateColumn: ERROR:  column "reverse_geocoded_at" of relation "points" already exists (PG::DuplicateColumn)
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:56:in `exec'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:56:in `block (2 levels) in raw_execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:1004:in `block in with_raw_connection'
/var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `block in raw_execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:1119:in `log'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `raw_execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:538:in `internal_execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:137:in `execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:27:in `execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:629:in `add_column'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:418:in `add_column'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration/default_strategy.rb:10:in `method_missing'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1059:in `block in method_missing'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1025:in `block in say_with_time'
/var/app/vendor/bundle/ruby/3.3.0/gems/benchmark-0.4.0/lib/benchmark.rb:304:in `measure'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1025:in `say_with_time'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1048:in `method_missing'
/var/app/db/migrate/20241202114820_add_reverse_geocoded_at_to_points.rb:7:in `change'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:994:in `exec_migration'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:978:in `block (2 levels) in migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/benchmark-0.4.0/lib/benchmark.rb:304:in `measure'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:977:in `block in migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in `with_connection'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:976:in `migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1190:in `migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1538:in `block in execute_migration_in_transaction'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1591:in `ddl_transaction'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1537:in `execute_migration_in_transaction'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1512:in `each'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1512:in `migrate_without_lock'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1457:in `block in migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1609:in `with_advisory_lock'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1457:in `migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1264:in `up'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1239:in `migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:205:in `block (4 levels) in prepare_all'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:565:in `with_temporary_pool'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:204:in `block (3 levels) in prepare_all'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:203:in `each'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:203:in `block (2 levels) in prepare_all'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:200:in `each'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:200:in `block in prepare_all'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:614:in `each'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:614:in `each_current_environment'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/tasks/database_tasks.rb:199:in `prepare_all'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/railties/databases.rake:399:in `block (2 levels) in <main>'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:156:in `invoke_rake'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:73:in `block in invoke'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:149:in `with_argv'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:69:in `invoke'
/var/app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands.rb:18:in `<main>'
/var/app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
Tasks: TOP => db:prepare
```
---
I can confirm that running with v0.19.3 for app and sidekiq is working, new container breaks...
Maybe I had an unstable configuration before the upgrade, not sure... Do you have any hint on how I could recover this?

**Comment by Freika** [comment]
The fix will be added in the next release today

**Comment by Freika** [comment]
Please update to 0.19.6 and let me know if it solved your problem

**Comment by elmuz** [comment]
Yes, new version solved, thank you.
