### ISSUE TITLE
0.19.5 crashlooping

### ISSUE THREAD

**Issue by shaman007** [Freika/dawarich#526]
**Describe the bug**
0.19.5 crashlooping

```
Environment: development
postgres-postgresql.db.svc.cluster.local (10.43.219.108:5432) open
Successfully installed rubygems-update-3.5.7
Installing RubyGems 3.5.7
  Successfully built RubyGem
  Name: bundler
  Version: 2.5.7
  File: bundler-2.5.7.gem
Bundler 2.5.7 installed
RubyGems 3.5.7 installed
Regenerating binstubs
Regenerating plugins



------------------------------------------------------------------------------

RubyGems installed the following executables:
	/usr/local/bin/gem
	/usr/local/bin/bundle
	/usr/local/bin/bundler

RubyGems system software updated
Successfully installed bundler-2.5.9
1 gem installed
Database dawarich_development already exists, skipping creation...
PostgreSQL is ready. Running database migrations...
[dotenv] Loaded [33m.env.development[0m
D, [2024-12-11T07:27:08.150059 #37] DEBUG -- :   [1m[36mActiveRecord::SchemaMigration Load (5.1ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
D, [2024-12-11T07:27:08.272391 #37] DEBUG -- :   [1m[36mActiveRecord::SchemaMigration Load (1.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Running DATA migrations...
[dotenv] Loaded [33m.env.development[0m
D, [2024-12-11T07:27:11.585395 #60] DEBUG -- :   [1m[35m (8.7ms)[0m  [1m[34mSELECT pg_try_advisory_lock(1212213197400985920)[0m
rake aborted!
ActiveRecord::ConcurrentMigrationError:  (ActiveRecord::ConcurrentMigrationError)

Cannot run migrations because another migration process is currently running.

/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1607:in `with_advisory_lock'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1457:in `migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/data_migrate-11.2.0/lib/data_migrate/migration_context.rb:15:in `up'
/var/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2/lib/active_record/migration.rb:1239:in `migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/data_migrate-11.2.0/lib/data_migrate/tasks/data_migrate_tasks.rb:26:in `migrate'
/var/app/vendor/bundle/ruby/3.3.0/gems/data_migrate-11.2.0/tasks/databases.rake:161:in `block (2 levels) in <main>'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => data:migrate
(See full trace by running task with --trace)
````

**Comment by Freika** [comment]
Did you try to stop the container and start them again? (not joking)

**Comment by shaman007** [comment]
Yes, several times. 19.3 is OK at the moment.

**Comment by shaman007** [comment]
This starts in 0.19.4 and the erros is in the sidekiq:
```
[dawarich-sidekiq] PostgreSQL is ready. Running database migrations...
[dawarich-sidekiq] [dotenv] Loaded .env.development
[dawarich-sidekiq] D, [2024-12-11T12:18:34.025667 #36] DEBUG -- : ActiveRecord::SchemaMigration Load (3.7ms) SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
[dawarich-sidekiq] D, [2024-12-11T12:18:34.126878 #36] DEBUG -- : ActiveRecord::SchemaMigration Load (1.8ms) SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
[dawarich-sidekiq] Running DATA migrations...
[dawarich-sidekiq] [dotenv] Loaded .env.development
[dawarich-sidekiq] D, [2024-12-11T12:18:37.367123 #59] DEBUG -- : (1.0ms) SELECT pg_try_advisory_lock(1212213197400985920)
[dawarich-sidekiq] rake aborted!
[dawarich-sidekiq] ActiveRecord::ConcurrentMigrationError: (ActiveRecord::ConcurrentMigrationError)
[dawarich-sidekiq]
[dawarich-sidekiq] Cannot run migrations because another migration process is currently running.
```

**Comment by shaman007** [comment]
Now after switching back and forth between .3 and .4, .3 sidekiq crashes as well! Maybe I need to drop something to make it think that migration is over or expired? Or trigger something?

**Comment by shaman007** [comment]
OKAY, got it back, so kinda post-mortem.

1. Destroyed all containers
2. in the psql, fould the lock and dropped it just in case:
```
ttrss=# SELECT * FROM pg_locks WHERE locktype = 'advisory';
 locktype | database | relation | page | tuple | virtualxid | transactionid |  classid  |   objid    | objsubid | virtualtransaction |   pid   |     mode      | granted | fastpath | waitstart
----------+----------+----------+------+-------+------------+---------------+-----------+------------+----------+--------------------+---------+---------------+---------+----------+-----------
 advisory |   664881 |          |      |       |            |               | 282240378 | 4280308032 |        1 | 5/4287834          | 2870929 | ExclusiveLock | t       | f        |
(1 row)

ttrss=# SELECT pg_terminate_backend(2870929);
 pg_terminate_backend
----------------------
 t
(1 row)

ttrss=# SELECT * FROM pg_locks WHERE locktype = 'advisory';
 locktype | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction | pid | mode | granted | fastpath | waitstart
----------+----------+----------+------+-------+------------+---------------+---------+-------+----------+--------------------+-----+------+---------+----------+-----------
(0 rows)
```
3. Started it without the Sidekiq
4. Had to wait about 10 minutes for migration
5. Restarted as usual.
6. Et voila!

Seems like there should be some logic for the sidekiq side to wait pationately until the migration is over.

**Comment by Freika** [comment]
> Seems like there should be some logic for the sidekiq side to wait pationately until the migration is over.

I'll look into it, meanwhile will keep this opened. Thank you!

**Comment by chrisl8** [comment]
If I understand correctly, sidekiq is closing because DB is doing a migration, and it will just keep looping until the migration is done, but then it will work?

**Comment by shaman007** [comment]
Seems so. I'd tested it bit other way. But it fires alerts so my guess no one (nearly) would just look 10+ minutes to wait for it to continue. Some lock that makes sidekiq wait would be useful.

**Comment by chrisl8** [comment]
Mine took over 20 minutes:

```
dawarich_app     | D, [2024-12-11T16:46:32.265730 #77] DEBUG -- :   TRANSACTION (0.2ms)  BEGIN
...
dawarich_app     | D, [2024-12-11T17:08:48.379836 #77] DEBUG -- :   Point Update All (1336087.0ms)  UPDATE "points" SET "reverse_geocoded_at" = $1 WHERE "points"."geodata" != $2  [["reverse_geocoded_at", "2024-12-11 16:46:32.286361"], ["geodata", "{}"]]
dawarich_app     | == 20241202125248 SetReverseGeocodedAtForPoints: migrated (1336.1581s) ========
dawarich_app     |
dawarich_app     | D, [2024-12-11T17:08:48.382768 #77] DEBUG -- :   DataMigrate::DataSchemaMigration Create (0.8ms)  INSERT INTO "data_migrations" ("version") VALUES ('20241202125248') RETURNING "version"
dawarich_app     | D, [2024-12-11T17:08:48.387195 #77] DEBUG -- :   TRANSACTION (3.3ms)  COMMIT
```

**Comment by shaman007** [comment]
Yeah, but if the K8S (or other orcherstration) reloads container every 30s of that period, at least should be some notice in the documentation. I was looking for a lock that is not being released and wes successfull because went to make some coffee.

**Comment by Freika** [comment]
> Mine took over 20 minutes:
> 
> ```
> dawarich_app     | D, [2024-12-11T16:46:32.265730 #77] DEBUG -- :   TRANSACTION (0.2ms)  BEGIN
> ...
> dawarich_app     | D, [2024-12-11T17:08:48.379836 #77] DEBUG -- :   Point Update All (1336087.0ms)  UPDATE "points" SET "reverse_geocoded_at" = $1 WHERE "points"."geodata" != $2  [["reverse_geocoded_at", "2024-12-11 16:46:32.286361"], ["geodata", "{}"]]
> dawarich_app     | == 20241202125248 SetReverseGeocodedAtForPoints: migrated (1336.1581s) ========
> dawarich_app     |
> dawarich_app     | D, [2024-12-11T17:08:48.382768 #77] DEBUG -- :   DataMigrate::DataSchemaMigration Create (0.8ms)  INSERT INTO "data_migrations" ("version") VALUES ('20241202125248') RETURNING "version"
> dawarich_app     | D, [2024-12-11T17:08:48.387195 #77] DEBUG -- :   TRANSACTION (3.3ms)  COMMIT
> ```

That would be my mistake, I optimistically expected this data migration to run in a few seconds maximum. I'll move it to the background job and will run any data migrations there in the future too
