### ISSUE TITLE
Update all stats no longer working

### ISSUE THREAD

**Issue by arne182** [Freika/dawarich#575]
**Describe the bug**

**Version**
0.2.1

**To Reproduce**
1. Go to status
2. Click on Update all 
3. <html>
<body>
<header style="color: rgb(223, 220, 215); background: rgb(163, 0, 0); padding: 0.5em 1.5em; font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="overflow-wrap: break-word; margin: 0.2em 0px; line-height: 1.1em; font-size: 2em;">TypeError in StatsController#update_all</h1></header><main role="main" id="container" style="box-sizing: border-box; width: 3838px; padding: 0px 1.5em; color: rgb(220, 217, 212); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="exception-message" style="padding: 8px 0px;"><div class="message" style="margin-bottom: 8px; line-height: 25px; font-size: 1.5em; font-weight: bold; color: rgb(255, 61, 61);">no implicit conversion of Symbol into Integer</div></div><div class="source " id="frame-source-0-0" style="border: 1px solid rgb(112, 104, 92); background: rgb(38, 42, 43); max-width: 978px;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#36</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background: rgb(51, 55, 58);">
34 35 36 37 38 39 | def update_all     current_user.years_tracked.each do \|year\|       year[:months].each do \|month\|         Stats::CalculatingJob.perform_later(           current_user.id, year[:year], Date::ABBR_MONTHNAMES.index(month)         )
-- | --

</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;"><code>Rails.root: /var/app</code></p><div id="traces-0"><a href="http://192.168.188.228:32568/stats#" onclick="hide('Framework-Trace-0');hide('Full-Trace-0');show('Application-Trace-0');; return false;" style="color: rgb(255, 61, 61);">Application Trace</a><span> </span>|<span> </span><a href="http://192.168.188.228:32568/stats#" onclick="hide('Application-Trace-0');hide('Full-Trace-0');show('Framework-Trace-0');; return false;" style="color: rgb(255, 61, 61);">Framework Trace</a><span> </span>|<span> </span><a href="http://192.168.188.228:32568/stats#" onclick="hide('Application-Trace-0');hide('Framework-Trace-0');show('Full-Trace-0');; return false;" style="color: rgb(255, 61, 61);">Full Trace</a><div id="Application-Trace-0" style="display: block;"><code class="traces" style="font-size: 11px;"><a class="trace-frames trace-frames-0" data-exception-object-id="67780" data-frame-id="0" href="http://192.168.188.228:32568/stats#" style="color: rgb(168, 160, 149); overflow-wrap: break-word;">app/controllers/stats_controller.rb:36:in `[]'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="67780" data-frame-id="1" href="http://192.168.188.228:32568/stats#" style="color: rgb(168, 160, 149); overflow-wrap: break-word;">app/controllers/stats_controller.rb:36:in `block in update_all'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="67780" data-frame-id="2" href="http://192.168.188.228:32568/stats#" style="color: rgb(168, 160, 149); overflow-wrap: break-word;">app/controllers/stats_controller.rb:35:in `each'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="67780" data-frame-id="3" href="http://192.168.188.228:32568/stats#" style="color: rgb(168, 160, 149); overflow-wrap: break-word;">app/controllers/stats_controller.rb:35:in `update_all'</a><br></code></div></div><h2 class="request-heading" style="color: rgb(255, 61, 61); line-height: 25px; margin-top: 30px;">Request</h2><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;"><b>Parameters</b>:</p><pre style="font-size: 11px; white-space: pre-wrap;">{"_method"=&gt;"put"}
</pre><div class="details" style="border: 1px solid rgb(106, 99, 87); border-radius: 4px; margin: 1em 0px; display: block; max-width: 978px;"><div class="summary" style="padding: 8px 15px; border-bottom: 1px solid rgb(106, 99, 87); display: block; border-top-color: rgb(106, 99, 87); border-right-color: rgb(106, 99, 87); border-left-color: rgb(106, 99, 87);"><a href="http://192.168.188.228:32568/stats#" onclick="return toggleSessionDump()" style="color: rgb(255, 61, 61);">Toggle session dump</a></div></div><div class="details" style="border: 1px solid rgb(106, 99, 87); border-radius: 4px; margin: 1em 0px; display: block; max-width: 978px;"><div class="summary" style="padding: 8px 15px; border-bottom: 1px solid rgb(106, 99, 87); display: block; border-top-color: rgb(106, 99, 87); border-right-color: rgb(106, 99, 87); border-left-color: rgb(106, 99, 87);"><a href="http://192.168.188.228:32568/stats#" onclick="return toggleEnvDump()" style="color: rgb(255, 61, 61);">Toggle env dump</a></div></div><h2 class="response-heading" style="color: rgb(255, 61, 61); line-height: 25px; margin-top: 30px;">Response</h2><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;"><b>Headers</b>:</p><pre style="font-size: 11px; white-space: pre-wrap;">None</pre></main>
</body>
</html>

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add logs from containers `dawarich_app` and `dawarich_sidekiq` to help explain your problem.

**Additional context**

**Comment by Freika** [comment]
@arne182 is this still an issue?
