### ISSUE TITLE
Error: too many files open

### ISSUE THREAD

**Issue by quentinClaudel** [Freika/dawarich#72]
**Describe the bug**
Thank you for this interesting application!
But I'm not able to make it work. The dawarich container keeps restarting because of this error:
```
node:internal/errors:465
16:57:01 css.1  |     ErrorCaptureStackTrace(err);
16:57:01 css.1  |     ^
16:57:01 css.1  | 
16:57:01 css.1  | Error: EMFILE: too many open files, watch '/var/app/app/assets/stylesheets/application.tailwind.css'
16:57:01 css.1  |     at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
16:57:01 css.1  |     at Object.watch (node:fs:2264:34)
16:57:01 css.1  |     at createFsWatchInstance (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:119:15)
16:57:01 css.1  |     at setFsWatchListener (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:166:15)
16:57:01 css.1  |     at NodeFsHandler._watchWithNodeFs (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:331:14)
16:57:01 css.1  |     at NodeFsHandler._handleFile (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:395:23)
16:57:01 css.1  |     at NodeFsHandler._addToNodeFs (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:637:21)
16:57:01 css.1  |     at async /snapshot/tailwindcss/node_modules/chokidar/index.js:451:21
16:57:01 css.1  |     at async Promise.all (index 0)
16:57:01 css.1  | Emitted 'error' event on FSWatcher instance at:
16:57:01 css.1  |     at FSWatcher._handleError (/snapshot/tailwindcss/node_modules/chokidar/index.js:647:10)
16:57:01 css.1  |     at NodeFsHandler._addToNodeFs (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:645:18)
16:57:01 css.1  |     at async /snapshot/tailwindcss/node_modules/chokidar/index.js:451:21
16:57:01 css.1  |     at async Promise.all (index 0) {
16:57:01 css.1  |   errno: -24,
16:57:01 css.1  |   syscall: 'watch',
16:57:01 css.1  |   code: 'EMFILE',
16:57:01 css.1  |   path: '/var/app/app/assets/stylesheets/application.tailwind.css',
16:57:01 css.1  |   filename: '/var/app/app/assets/stylesheets/application.tailwind.css'
16:57:01 css.1  | }
16:57:02 css.1  | exited with code 0
16:57:02 system | sending SIGTERM to all processes
```

It's a fresh install. My server is a virtual machine running on top of Proxmox. I tried to delete the volumes and started it again, but the same issue happened.

**Version**
I use the latest version: 0.7.1.

**To Reproduce**
Run `docker compose up` on a server.

**Expected behavior**
dawarich should start successfully.

**Comment by quentinClaudel** [comment]
The error came from a VM configuration issue. Sorry for the inconvenience.

**Comment by a-camacho** [comment]
How did you solve it ?

**Comment by quentinClaudel** [comment]
My limits needed to be increased. Here is an interesting article about it: https://www.howtogeek.com/805629/too-many-open-files-linux/
