### ISSUE TITLE
Error at first deployment

### ISSUE THREAD

**Issue by janaxhell** [Freika/dawarich#76]
**Describe the bug**
As soon as I deploy and start the container it closes with an error.

**Version**
Lastest available

**To Reproduce**
1. Deploy stack

**Expected behavior**
To just work

**Screenshots**

**Logs**
```
Environment: development
dawarich_db (172.32.0.4:5432) open
Latest version already installed. Done.
Successfully installed bundler-2.5.9
1 gem installed
Creating database dawarich_development...
Database 'dawarich_development' already exists
Database 'dawarich_test' already exists
PostgreSQL is ready. Running database migrations...
Running DATA migrations...
15:53:19 web.1  | started with pid 40
15:53:19 css.1  | started with pid 41
15:53:21 web.1  | => Booting Puma
15:53:21 web.1  | => Rails 7.1.3.4 application starting in development 
15:53:21 web.1  | => Run `bin/rails server --help` for more startup options
15:53:21 web.1  | Puma starting in single mode...
15:53:21 web.1  | * Puma version: 6.4.2 (ruby 3.2.3-p157) ("The Eagle of Durango")
15:53:21 web.1  | *  Min threads: 5
15:53:21 web.1  | *  Max threads: 5
15:53:21 web.1  | *  Environment: development
15:53:21 web.1  | *          PID: 40
15:53:21 web.1  | * Listening on http://0.0.0.0:3000
15:53:21 web.1  | Use Ctrl-C to stop
15:53:23 css.1  | 
15:53:23 css.1  | Rebuilding...
15:53:23 css.1  | 
15:53:23 css.1  | ??   daisyUI 4.7.3
15:53:23 css.1  | ?? ?? 2 themes added		https://daisyui.com/docs/themes
15:53:23 css.1  | ?? ?? Support daisyUI project:	https://opencollective.com/daisyui
15:53:23 css.1  | 
15:53:24 css.1  | node:internal/errors:465
15:53:24 css.1  |     ErrorCaptureStackTrace(err);
15:53:24 css.1  |     ^
15:53:24 css.1  | 
15:53:24 css.1  | Error: EMFILE: too many open files, watch '/var/app/app/assets/stylesheets/application.tailwind.css'
15:53:24 css.1  |     at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
15:53:24 css.1  |     at Object.watch (node:fs:2264:34)
15:53:24 css.1  |     at createFsWatchInstance (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:119:15)
15:53:24 css.1  |     at setFsWatchListener (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:166:15)
15:53:24 css.1  |     at NodeFsHandler._watchWithNodeFs (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:331:14)
15:53:24 css.1  |     at NodeFsHandler._handleFile (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:395:23)
15:53:24 css.1  |     at NodeFsHandler._addToNodeFs (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:637:21)
15:53:24 css.1  |     at async /snapshot/tailwindcss/node_modules/chokidar/index.js:451:21
15:53:24 css.1  |     at async Promise.all (index 0)
15:53:24 css.1  | Emitted 'error' event on FSWatcher instance at:
15:53:24 css.1  |     at FSWatcher._handleError (/snapshot/tailwindcss/node_modules/chokidar/index.js:647:10)
15:53:24 css.1  |     at NodeFsHandler._addToNodeFs (/snapshot/tailwindcss/node_modules/chokidar/lib/nodefs-handler.js:645:18)
15:53:24 css.1  |     at async /snapshot/tailwindcss/node_modules/chokidar/index.js:451:21
15:53:24 css.1  |     at async Promise.all (index 0) {
15:53:24 css.1  |   errno: -24,
15:53:24 css.1  |   syscall: 'watch',
15:53:24 css.1  |   code: 'EMFILE',
15:53:24 css.1  |   path: '/var/app/app/assets/stylesheets/application.tailwind.css',
15:53:24 css.1  |   filename: '/var/app/app/assets/stylesheets/application.tailwind.css'
15:53:24 css.1  | }
15:53:25 css.1  | exited with code 0
15:53:25 system | sending SIGTERM to all processes
15:53:25 web.1  | - Gracefully stopping, waiting for requests to finish
15:53:25 web.1  | Exiting
15:53:25 web.1  | terminated by SIGTERM

```

**Additional context**
This is my compose, I've changed network and mounted folders

```
version: '3'
networks:
  omv2b:
    external: true
services:
  dawarich_redis:
    image: redis:7.0-alpine
    command: redis-server
    networks:
      - omv2b
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/dawarich/shared_data/redis:/var/shared/redis
  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/dawarich/db_data:/var/lib/postgresql/data
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/dawarich/shared_data:/var/shared
    networks:
      - omv2b
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/dawarich/gem_cache:/usr/local/bundle/gems
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/dawarich/public:/var/app/public
    networks:
      - omv2b
    ports:
      - 3556:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: 192.168.1.164
      TIME_ZONE: Europe/Rome
    depends_on:
      - dawarich_db
      - dawarich_redis
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/dawarich/gem_cache:/usr/local/bundle/gems
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/dawarich/public:/var/app/public
    networks:
      - omv2b
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app

volumes:
  db_data:
  gem_cache:
  shared_data:
  public:


```

**Comment by a-camacho** [comment]
I solved this issue changing some parameters in host machine (Debian VM) :

```
fs.inotify.max_user_watches=524288
fs.inotify.max_user_instances=512
```

**Comment by janaxhell** [comment]
> I solved this issue changing some parameters in host machine (Debian VM) :
> 
> ```
> fs.inotify.max_user_watches=524288
> fs.inotify.max_user_instances=512
> ```

Yes, it worked, thank you!

**Comment by janaxhell** [comment]
!Solved
As per #79 I just had to set APPLICATION_HOST variable to point at my public domain, so this combined with the notify variables made it work.

**Comment by Freika** [comment]
@janaxhell please show contents of your docker-compose.yml :)

**Comment by janaxhell** [comment]
It's in my first post. The only difference now is that I have changed the HOST env to my domain. It worked fine, until I decided to change the postgres password in the compose. After that it stopped working.

**Comment by janaxhell** [comment]
In a somewhat magic way I have solved this:
- updated stack with new v0.8
- `sysctl fs.inotify.max_user_instances=8192` (it was 512 before)
- set the first APPLICATION_HOST env to my domain WITHOUT "https://", just the plain URL like ccc.ccc.ccc
- set the second APPLICATION_HOST env to my local service IP http://192.168.1.168:3556

After doing this, Dawarich was again reachable via my cloudflare doamin. 
This is the log:

```
RubyGems installed the following executables:
	/usr/local/bin/gem
	/usr/local/bin/bundle
	/usr/local/bin/bundler

RubyGems system software updated
Fetching bundler-2.5.9.gem
Successfully installed bundler-2.5.9
1 gem installed

A new release of RubyGems is available: 3.5.7 ? 3.5.14!
Run `gem update --system 3.5.14` to update your installation.

Creating database dawarich_development...
Database 'dawarich_development' already exists
Database 'dawarich_test' already exists
PostgreSQL is ready. Running database migrations...
Running DATA migrations...
10:51:08 web.1  | started with pid 50
10:51:08 css.1  | started with pid 51
10:51:10 web.1  | => Booting Puma
10:51:10 web.1  | => Rails 7.1.3.4 application starting in development 
10:51:10 web.1  | => Run `bin/rails server --help` for more startup options
10:51:10 web.1  | Puma starting in single mode...
10:51:10 web.1  | * Puma version: 6.4.2 (ruby 3.2.3-p157) ("The Eagle of Durango")
10:51:10 web.1  | *  Min threads: 5
10:51:10 web.1  | *  Max threads: 5
10:51:10 web.1  | *  Environment: development
10:51:10 web.1  | *          PID: 50
10:51:10 web.1  | * Listening on http://0.0.0.0:3000
10:51:10 web.1  | Use Ctrl-C to stop
10:51:12 css.1  | 
10:51:12 css.1  | Rebuilding...
10:51:12 css.1  | 
10:51:12 css.1  | ??   daisyUI 4.7.3
10:51:13 css.1  | ?? ?? 2 themes added		https://daisyui.com/docs/themes
10:51:13 css.1  | ?? ? Star daisyUI on GitHub	https://github.com/saadeghi/daisyui
10:51:13 css.1  | 
10:51:14 css.1  | 
10:51:14 css.1  | Done in 1810ms.
10:51:21 web.1  | Started GET "/" for 162.158.129.147 at 2024-06-26 10:51:21 +0000
10:51:21 web.1  |   ActiveRecord::SchemaMigration Load (1.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
10:51:21 web.1  | Processing by HomeController#index as HTML
10:51:21 web.1  |   Rendering layout layouts/application.html.erb
10:51:21 web.1  |   Rendering home/index.html.erb within layouts/application
10:51:21 web.1  |   Rendered home/index.html.erb within layouts/application (Duration: 1.1ms | Allocations: 511)
10:51:21 web.1  |   Rendered application/_favicon.html.erb (Duration: 4.4ms | Allocations: 3879)
10:51:22 web.1  |   Rendered shared/_navbar.html.erb (Duration: 230.5ms | Allocations: 6423)
10:51:22 web.1  |   Rendered shared/_flash.html.erb (Duration: 3.4ms | Allocations: 196)
10:51:22 web.1  |   Rendered shared/_footer.html.erb (Duration: 5.5ms | Allocations: 186)
10:51:22 web.1  |   Rendered layout layouts/application.html.erb (Duration: 781.2ms | Allocations: 225434)
10:51:22 web.1  | Completed 200 OK in 809ms (Views: 788.3ms | ActiveRecord: 0.0ms | Allocations: 233284)
10:51:22 web.1  | 
10:51:22 web.1  | 
10:51:25 web.1  | Started GET "/images/bg-image.jpg" for 172.71.114.133 at 2024-06-26 10:51:25 +0000
10:51:26 web.1  |   
10:51:26 web.1  | ActionController::RoutingError (No route matches [GET] "/images/bg-image.jpg"):
```

But I have to add that prior to my mess with postgres password, it worked with both fs.inotify.max_user_instances=512 and APPLICATION_HOST using "https://" prefix. This time it won't work until I removed "https://".

**Comment by Freika** [comment]
@janaxhell you're right about removing the protocol from APPLICATION_HOST value, but I wonder what you mean by "first APPLICATION_HOST" and "second APPLICATION_HOST"? Currently docker-compose.yml accepts only one value as a host and I plan to change it later so it can accept multiple values as an array (say, the IP address AND domain name)

So, eventually, you've fixed your problem, right?

**Comment by janaxhell** [comment]
Look at the compose above, it has 2 APPLICATION_HOST entries. I have just copypasted it from this git and modified the volumes, but all the rest was already there. 
Anyway, yes, it works. Although on my S22 it seems it only works if I open the app, not always in the background. I suppose it's just a quirk for the early stages.

**Comment by Freika** [comment]
Got it, you're referring to APPLICATION_HOST for app and sidekiq containers. I'll add a comment so in future users would not provide protocol in this variable value.

Glad it worked anyway!

> Although on my S22 it seems it only works if I open the app, not always in the background. I suppose it's just a quirk for the early stages.

Is this about an app on your phone?

**Comment by janaxhell** [comment]
> Got it, you're referring to APPLICATION_HOST for app and sidekiq containers. I'll add a comment so in future users would not provide protocol in this variable value.

So is it ok to set the first as public domain my.sit.com and the second to local IP? 

> Is this about an app on your phone?

Yes, sorry, I meant Owntracks for Android in my little experiments worked only when the app was running. When it was only an icon, it did not track me. Dawarich registered only the first route, not the second.

**Comment by Freika** [comment]
> So is it ok to set the first as public domain my.site.com and the second to local IP?

It doesn't really make sense, because they are supposed to be the same, as they represent the same value in the code of the application. The thing is, the value you're setting in `dawarich_sidekiq` section probably won't be used in 99% cases, and we have to provide it just to play on the safe side. So for now, I'd recommend to set same value in both sections (`dawarich_app` and `dawarich_sidekiq`), I think I'll implement support for multiple values by the end of this week.

> Yes, sorry, I meant Owntracks for Android in my little experiments worked only when the app was running. When it was only an icon, it did not track me. Dawarich registered only the first route, not the second.

Unfortunately, we can only configure Owntracks (or Overland for that matter) and hope they will track the location history, but we can't alter their behavior in any way. If Dawarich will eventually grow big enough of a project and will have its own mobile application, more things will be under developer's control (hopefully), but I can't even say at this point whether Dawarich ever have a mobile app :)

**Comment by Freika** [comment]
Closing this, let me know if this still an ongoing problem

**Comment by FunnyPocketBook** [comment]
In case someone is using Unraid: Use the tips and tweaks plugin to change the inotify.max_user_instances variable
